- README.md
build step still references github.com/hashicorp
> Fix Readme build step

- website/docs/d/publiccloud_region.html.markdown
Related to https://github.com/terraform-providers/terraform-provider-ovh/pull/4
> docs: Document deprecation of fields

- website/docs/r/ovh_domain_zone_record.html.markdown
- website/ovh.erb
Hi,
This PR is to fix a markdown with a mistake in the templating.
I've also added some missing links to the navigation index.
> Fixed documentation

- website/docs/r/ovh_domain_zone_record.html.markdown
> Fix doc on zone record resource

- vendor/github.com/ovh/go-ovh/ovh/configuration.go
- vendor/github.com/ovh/go-ovh/ovh/ovh.go
- vendor/vendor.json
Hi,
The vendorized lib github.com/ovh/go-ovh/ovh has not been updated for a while.
I would like to have the fix (https://github.com/ovh/go-ovh/commit/34b9ffdf98692f9e9b57724d180549f88725b605).
Therefore can we update the lib?
Thanks.
> vendor: update github.com/ovh/go-ovh/ovh

- ovh/resource_ovh_domain_zone_redirection.go
- ovh/resource_ovh_domain_zone_redirection_test.go
> Fix acc tests on ovh_domain_zone_redirection

- ovh/config.go
> Add OVH US api endpoint

- ovh/provider.go
- ovh/resource_ovh_iploadbalancing_refresh.go
- website/docs/r/iploadbalancing_refresh.markdown
fixes https://github.com/terraform-providers/terraform-provider-ovh/issues/59
> adds loadbalancer refresh

- ovh/resource_ovh_iploadbalancing_tcp_frontend.go
- ovh/resource_ovh_iploadbalancing_tcp_frontend_test.go
A debug line has been forgotten in code base
A test has been added to check test and fix
the misbehavior
> r/iplb_frontend: fix default farm id issue

- website/docs/d/publiccloud_region.html.markdown
- website/docs/d/publiccloud_regions.html.markdown
- website/docs/r/publiccloud_private_network.html.markdown
- website/docs/r/publiccloud_private_network_subnet.html.markdown
- website/docs/r/publiccloud_user.html.markdown
- website/docs/r/vrack_publiccloud_attachment.html.markdown
> docs: Make deprecations more visible

- .travis.yml
> bump travis setup to xenial + go 1.13.x

- ovh/provider_test.go
- ovh/resource_ovh_iploadbalancing_tcp_farm_test.go
> testing: skip acc tests if required env var not present

- ovh/import_iploadbalancing_http_farm_server_test.go
- ovh/import_iploadbalancing_http_farm_test.go
- ovh/import_iploadbalancing_http_frontend_test.go
- ovh/import_iploadbalancing_http_route_rule_test.go
- ovh/import_iploadbalancing_http_route_test.go
- ovh/import_iploadbalancing_tcp_farm_server_test.go
- ovh/import_iploadbalancing_tcp_farm_test.go
- ovh/import_iploadbalancing_tcp_frontend_test.go
- ovh/resource_ovh_iploadbalancing_http_farm.go
- ovh/resource_ovh_iploadbalancing_http_farm_server.go
- ovh/resource_ovh_iploadbalancing_http_farm_test.go
- ovh/resource_ovh_iploadbalancing_http_frontend.go
- ovh/resource_ovh_iploadbalancing_http_route.go
- ovh/resource_ovh_iploadbalancing_http_route_rule.go
- ovh/resource_ovh_iploadbalancing_tcp_farm.go
- ovh/resource_ovh_iploadbalancing_tcp_farm_server.go
- ovh/resource_ovh_iploadbalancing_tcp_farm_test.go
- ovh/resource_ovh_iploadbalancing_tcp_frontend.go
Add importers for all iploadbalancing resources
Refactor read function of iplb Tcp & Http farm
Add tests for iplb importers
Fix typo in 'oco' probe type
Small lint fixes for iplb
> feat(iploadbalancing): Add iploadbalancing importers

- ovh/data_source_ovh_dedicated_server.go
- website/docs/d/dedicated_server.html.markdown
Adds `ips` property with all ip blocks assigned to dedicated server.
> Fetch all IPs for dedicated servers

- ovh/config.go
Added all endpoints available in ovh lib. Provider seems to work just fine for Kimsufi API.
Fixes #147
> Add Kimsufi and SoYouStart api endpoints

- ovh/data_source_ovh_vps.go
Somehow the vps datasource got broken.This PR fixes it
> bugfix(data_source_ovh_vps): Fix erroneous types

- website/docs/index.html.markdown
> OVH to OVHcloud

- ovh/resource_ovh_cloud_project_kube.go
- ovh/resource_ovh_cloud_project_kube_test.go
> r/cloud_project_kube: Fix issue with empty version

- ovh/data_source_ovh_iploadbalancing.go
Do not search for iploadbalancing service when exact service_name was passed
> [Iploadbalancing] Do not search when service_name was passed 

- ovh/provider.go
- ovh/provider_test.go
- ovh/resource_ip_reverse.go
- ovh/resource_ip_reverse_test.go
- ovh/types_ip.go
- website/docs/r/ip_reverse.html.markdown
> r/ip_reverse: rewrite of the resource

- ovh/config.go
- ovh/helpers/helpers.go
> Add missing Ovh subsidiaries

- website/docs/index.html.markdown
Signed-off-by: Wilfried Roset <wilfriedroset@users.noreply.github.com>
> Add OVH_ENDPOINT in alternative configuration of the provider

- README.md
- website/docs/index.html.markdown
Add instructions on how to use a freshly terraform-provider-ovh in a test configuration
> Add instructions on how to use a locally built provider

- ovh/resource_cloud_project_containerregistry.go
Hello,
I made some tests on containerregistry terraform module and it works very well !
I just found a small typo in the pending status that triggers error when upgrading plan.
Thomas
> fix containerregistry plan update pending status

- website/docs/r/cloud_project_database.html.markdown
> fix: esential to essential

- website/docs/d/cloud_project_kube.html.markdown
fix missing doc for data kube nested object customization
> fix missing doc for data kube nested object customization

- ovh/resource_cloud_project_kube.go
- ovh/resource_cloud_project_kube_helpers.go
This is PR does not contains acceptance tests relative to import mecanism
> add kubeconfig in state when import

- ovh/resource_cloud_project_database.go
- website/docs/d/cloud_project_database.html.markdown
- website/docs/r/cloud_project_database.html.markdown
- Fix datasource doc
- Add Nodes sub attributs in Doc
- Add tips on Network_id
> improve cloud_project_database doc

- website/docs/r/cloud_project_kube_nodepool.html.markdown
Fixing the import command for nodes pool
> fix import ovh_cloud_project_kube_nodepool

- ovh/provider.go
- ovh/resource_vrack_dedicated_server.go
- website/docs/r/dedicated_server_install_task.html.markdown
- website/docs/r/vrack_dedicated_server.html.markdown
- website/docs/r/vrack_dedicated_server_interface.html.markdown
- website/ovh.erb
Reverts ovh/terraform-provider-ovh#323
> Revert "refactor: remove ovh_vrack_dedicated_server"

- ovh/resource_cloud_project_database.go
- ovh/types_cloud_project_database.go
Fix Disk Size and type that which currently prevent to update service
> fix disk type and size

- ovh/data_dbaas_logs_input_engine.go
- ovh/data_dbaas_logs_input_engine_test.go
- ovh/data_dbaas_logs_output_graylog_stream.go
- ovh/data_dbaas_logs_output_graylog_stream_test.go
- ovh/types_dbaas_logs.go
- website/docs/d/dbaas_logs_input_engine.html.markdown
- website/docs/d/dbaas_logs_output_graylog_stream.html.markdown
Hello,
This PR will handle the new input engine endpoint of dbaas/logs api and also fix various tests.
Thanks for your time on this.
Signed-off-by: Pierre De Paepe <pierre.de-paepe@ovhcloud.com>
> fix: input engine and logs tests

- ovh/data_me_installation_template.go
- ovh/resource_me_installation_template.go
- ovh/types_installation_template.go
- website/docs/d/me_installation_template.html.markdown
- website/docs/r/me_installation_template.html.markdown
And improve also the documentation
> Remove uefi & gpt for installation template

- website/docs/r/ovh_domain_zone_record.html.markdown
Update documentation to explain how to get the zone record id to import an existing record.
> Clarify how to get zone id for ovh_domain_zone_record import 

- ovh/data_cloud_project_kube_nodepool.go
- ovh/resource_cloud_project_kube_nodepool.go
- ovh/types_cloud_project_kube_nodepool.go
add missing read template from cloud response
> fix node pool read template

- ovh/data_cloud_project_kube_nodepool.go
- ovh/resource_cloud_project_kube_nodepool.go
- ovh/types_cloud_project_kube_nodepool.go
fix error text
fix same schema resource/data
fix deserialization
> fix 3 issue for nodepool deserialization

- website/docs/r/cloud_project.html.markdown
Clarify documentation based on issue https://github.com/ovh/terraform-provider-ovh/issues/342
> Clarify cloud project import

- ovh/data_order_cart.go
Solve issue https://github.com/ovh/terraform-provider-ovh/issues/331
> update expire time format to RFC3339 constant to avoid local time issues

- ovh/provider.go
- ovh/provider_test.go
- ovh/resource_cloud_project_workflow_backup.go
- ovh/resource_cloud_project_workflow_backup_test.go
- ovh/resource_hosting_privatedatabase_test.go
- ovh/resource_vrack_ip_loadbalancing_test.go
- ovh/types_cloud_project_workflow_backup.go
- website/docs/index.html.markdown
- website/docs/r/cloud_project_workflow_backup.html.markdown
and fix 2 other resources for sweeping
> Add WorkflowBackup resource

- ovh/data_cloud_project_database.go
- ovh/data_cloud_project_database_databases.go
- ovh/resource_cloud_project_database.go
- ovh/resource_cloud_project_database_m3db_user.go
- ovh/resource_cloud_project_database_mongodb_user.go
- ovh/resource_cloud_project_database_opensearch_user.go
- ovh/resource_cloud_project_database_postgresql_user.go
- ovh/resource_cloud_project_database_redis_user.go
- ovh/resource_cloud_project_database_user.go
- ovh/types_cloud_project_database.go
- website/docs/d/cloud_project_database.html.markdown
- website/docs/d/cloud_project_database_users.html.markdown
- website/docs/r/cloud_project_database.html.markdown
- website/docs/r/cloud_project_database_m3db_user.html.markdown
- website/docs/r/cloud_project_database_opensearch_user.html.markdown
- website/docs/r/cloud_project_database_postgresql_user.html.markdown
- website/docs/r/cloud_project_database_redis_user.html.markdown
- website/docs/r/cloud_project_database_user.html.markdown
- Add Advanced Configuration (Resource/datasource/doc) (https://github.com/ovh/terraform-provider-ovh/issues/335)
- Manage avnadmin user (Resource)
- Some fix and  factorization for user resources
> add advanced config and manage avnadmin user

- website/docs/r/cloud_project_kube.html.markdown
- website/docs/r/cloud_project_kube_iprestrictions.html.markdown
- website/docs/r/cloud_project_kube_nodepool.html.markdown
- website/docs/r/cloud_project_kube_oidc.html.markdown
Update various Managed Kubernetes Service documentation regarding destructing operations.
Related to #371.
> fix(kube): Update documentation with destructing operations

- website/docs/d/cloud_project_database.html.markdown
- website/docs/d/cloud_project_database_ip_restrictions.html.markdown
- website/docs/d/cloud_project_databases.html.markdown
- website/docs/d/cloud_project_failover_ip_attach.html.markdown
- website/docs/r/cloud_project_database.html.markdown
- website/docs/r/cloud_project_database_integration.html.markdown
- website/docs/r/cloud_project_database_m3db_user.html.markdown
- website/docs/r/cloud_project_database_mongodb_user.html.markdown
- website/docs/r/cloud_project_database_opensearch_user.html.markdown
- website/docs/r/cloud_project_database_postgresql_user.html.markdown
- website/docs/r/cloud_project_database_user.html.markdown
- website/docs/r/dedicated_nasha_partition.markdown
- website/docs/r/dedicated_nasha_partition_access.markdown
- website/docs/r/dedicated_nasha_partition_snapshot.markdown
- website/docs/r/iploadbalancing_http_farm.html.markdown
- website/docs/r/iploadbalancing_http_farm_server.html.markdown
- website/docs/r/iploadbalancing_http_frontend.html.markdown
> Add hcl format when missing

- website/docs/r/cloud_project_database.html.markdown
Add an example for grafana DB creation in the documentation for `ovh_cloud_project_database`.
> [Documentation] Add grafana example for `ovh_cloud_project_database`

- ovh/types_cloud_project_database.go
Fix compilation issue with the recently modified function postCloudProjectDatabaseUser
> fix (managed databases) Reset avnadmin grafana password

- ovh/resource_cloud_project_kube_oidc.go
- ovh/resource_dedicated_ceph_acl_test.go
2 fixes :
- one in the ceph acl sweepers
- one related to go 1.20 upgrade
* Terraform version: `terraform version`: Terraform v1.4.6
> Tests fixes

- website/docs/r/cloud_project_kube.html.markdown
Update the documentation example that show how to output in a simplest way a kubeconfig file.
> feat: update the documentation example with the new simplest way to output a kubeconfig file

- ovh/resource_cloud_project_database.go
- ovh/resource_cloud_project_database_integration.go
- ovh/resource_cloud_project_database_kafka_topic.go
- ovh/resource_cloud_project_database_m3db_namespace.go
- ovh/resource_cloud_project_database_redis_user.go
- ovh/types_cloud_project_database.go
Remove warning in Databases resources
- Improvement (improve existing resource(s) or datasource(s))
> remove unnecessary warning in database resources

- ovh/resource_iam_policy_test.go
fixes the iam policies sweeper
> fix: iam policy sweep

- website/docs/d/iam_policies.html.markdown
- website/docs/d/iam_policy.html.markdown
- website/docs/d/iam_reference_actions.html.markdown
- website/docs/d/iam_reference_resource_type.markdown
- website/docs/r/iam_policy.html.markdown
IAM resources had a warning about a private bets.
The IAM is now in open beta and available to everyone, so the warning is not needed anymore
> doc: remove warning about IAM beta

- website/docs/r/iploadbalancing_http_farm.html.markdown
- website/docs/r/iploadbalancing_http_farm_server.html.markdown
- website/docs/r/iploadbalancing_http_frontend.html.markdown
- website/docs/r/iploadbalancing_http_route.html.markdown
- website/docs/r/iploadbalancing_http_route_rule.html.markdown
- website/docs/r/iploadbalancing_tcp_farm.html.markdown
- website/docs/r/iploadbalancing_tcp_farm_server.html.markdown
- website/docs/r/iploadbalancing_tcp_frontend.html.markdown
- website/docs/r/iploadbalancing_tcp_route.html.markdown
- website/docs/r/iploadbalancing_tcp_route_rule.html.markdown
Add documentation on the import of iplb resources (farm, server, route, rule)
Fixes #429 
- [ X] Documentation update
N/A
> Add import documentation on iplb resources

- website/docs/d/order_cart.html.markdown
- website/docs/r/cloud_project.html.markdown
- website/docs/r/hosting_privatedatabase.html.markdown
- website/docs/r/ip_service.html.markdown
- website/docs/r/iploadbalancing.html.markdown
- website/docs/r/ovh_domain_zone.html.markdown
- website/docs/r/vrack.html.markdown
This PR adds detail about what is an OVHcloud subsidiary and where to find supported values.
No tests. this is a documentation change.
> doc: Detail what is an OVHcloud subsidiary

- website/docs/r/me_ssh_key.html.markdown
> fix: PR 467 (typo)

- ovh/data_cloud_project_user_s3_policy_test.go
A change in the API has lead to change in the order of the json attributes of the Policy. This PR defines a [Custom Check Function](https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests/teststep#custom-check-functions) to handle the comparison of the json.
> fix TestAccDataCloudProjectUserS3Policy_basic

- CHANGELOG.md
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
```hcl
xx = "yy"
zz = "aa"
}
```
> Update changelog for v0.35.0

- .cds/terraform-provider-ovh-post-sweepers.pip.yml
- .cds/terraform-provider-ovh-pre-sweepers.pip.yml
- .cds/terraform-provider-ovh.yml
This PR updates the testing workflow to run tests in parallel and reduce the build time.
Some tests that already didn't pass before are still not passing and will be fixed in further PRs.
- Acceptance tests ran automatically on the branch
> chore: Parallellize acceptance tests

- website/docs/r/vrack.html.markdown
Add vrack import documentation that was missing
Fixes #512
N/A
> add vrack import doc

- website/docs/r/cloud_project.html.markdown
Add documentation to order cloud HDS certification
> doc: how to order hds certification at cloud project creation

- .cds/terraform-provider-ovh-check.pip.yml
- .cds/terraform-provider-ovh-post-sweepers.pip.yml
- .cds/terraform-provider-ovh-pre-sweepers.pip.yml
- .cds/terraform-provider-ovh-testacc.pip.yml
- ovh/data_iam_permissions_group_test.go
- ovh/resource_iam_permissions_group_test.go
Update vendor to fix broken CI.
> fix: Update CI workers model and update vendor

- ovh/data_cloud_project_kube_nodepool.go
- ovh/data_cloud_project_kube_nodepool_test.go
- ovh/helpers/helpers.go
- ovh/resource_cloud_project_kube_nodepool.go
- ovh/resource_cloud_project_kube_nodepool_test.go
- ovh/types_cloud_project_kube_nodepool.go
- website/docs/d/cloud_project_kube_nodepool.html.markdown
- website/docs/r/cloud_project_kube_nodepool.html.markdown
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #506 
* Terraform v1.6.6 on linux_amd64
> fix: #506 Add autoscaling settings

- ovh/order.go
- ovh/types_order_cart.go
Permit to use fidelity account to pay order if no payment mean registered yet
* Terraform version: `terraform version`: Terraform v1.5.7
```terraform
data "ovh_order_cart" "mycart" {
ovh_subsidiary = data.ovh_me.myaccount.ovh_subsidiary
}
data "ovh_order_cart_product_plan" "cloud" {
cart_id        = data.ovh_order_cart.mycart.id
price_capacity = "renew"
product        = "cloud"
plan_code      = "project.2018"
}
resource "ovh_cloud_project" "my_cloud_project" {
ovh_subsidiary = data.ovh_order_cart.mycart.ovh_subsidiary
description    = "my cloud project" …
```
> feat: permit to create cloud project without payment method

- CHANGELOG.md
> Add CHANGELOG for 0.37.0

- ovh/resource_domain_zone_record.go
```hcl
xx = "yy"
zz = "aa"
}
```
> fix: domain_zone_record: force recreate resource when zone is modified

- ovh/provider.go
- ovh/resource_cloud_project_gateway.go
- ovh/resource_cloud_project_gateway_test.go
- ovh/types_cloud.go
- website/docs/r/cloud_project_gateway.html.markdown
check https://github.com/ovh/terraform-provider-ovh/pull/358/
i've just split the previsou MR into just one feature 
i removed the interface stuff, because atm , i don't have time pass more time.
will come back later to finish the rest of the initial MR
Related: #358
> feat(cloud): add gateway ressource

- website/docs/r/cloud_project_kube.html.markdown
Improve documentation on private network. 
N/A
> improve private network mks doc

- .cds/terraform-provider-ovh.yml
- ovh/data_cloud_project_database_ip_restrictions.go
- ovh/import_cloud_project_database_test.go
- ovh/resource_cloud_project_database_ip_restriction.go
- website/docs/d/cloud_project_database_ip_restrictions.html.markdown
- website/docs/r/cloud_project_database_ip_restriction.html.markdown
Fix database import test
Add Warning message in Documentation and Deprecation Message
Remove tests for deprecated ip restriction resources to avoid error
> Fix database import test and remove tests to deprecated resource

- website/docs/d/cloud_project_kube_oidc.html.markdown
- website/docs/r/cloud_project_kube_oidc.html.markdown
Fixes [#549](https://github.com/ovh/terraform-provider-ovh/issues/549) (issue)
> fix: Use the correct field names in resource/datasource ovh_cloud_project_kube_oidc doc

- ovh/resource_cloud_project_user.go
Check if user role exist with the API
```
➜ make testacc TESTARGS="-run TestAccCloudProjectUser_withRole"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccCloudProjectUser_withRole -timeout 600m -p 10
?       github.com/ovh/terraform-provider-ovh   [no test files]
?       github.com/ovh/terraform-provider-ovh/ovh/helpers       [no test files]
?       github.com/ovh/terraform-provider-ovh/ovh/types [no test files]
=== RUN   TestAccCloudProjectUser_withRole
provider_test.go:387: Read Cloud Project /cloud/project/bad3308a4b4d4dcba4d15d5b082d7225 -> status: 'ok', desc: 'Production'
--- PASS: TestAccCloudProjectUser_withRole (24.55s)
=== RUN   TestAccCloudProjectUser_withRoles
provider_test.go:387: Read Cloud Project …
```
> Check user role exist

- ovh/resource_cloud_project_network_private.go
- ovh/resource_cloud_project_network_private_test.go
- ovh/types_cloud.go
- ovh/types_cloud_project_vrack.go
Add possibility to update network private regions
Fixes [#402](https://github.com/ovh/terraform-provider-ovh/issues/402)
Create :
```hcl
resource "ovh_cloud_project_network_private" "network" {
name         = "network"
regions      = ["GRA11", "GRA9"]
vlan_id      = 0
}
```
Output
```
+ resource "ovh_cloud_project_network_private" "network" {
+ id                 = (known after apply)
+ name               = "network"
+ regions            = [
+ "GRA11",
+ "GRA9",
]
+ regions_attributes = (known after apply)
+ regions_status     = (known after apply)
+ service_name       = "xxxxxxx"
+ status             = (known after apply)
+ type               = (known after apply)
+ vlan_id            = 0
}
Plan: 1 to add, 0 to change, 0 to destroy.
```
Update …
> Update private network & update test

- ovh/resource_cloud_project_gateway.go
- website/docs/r/cloud_project_gateway.html.markdown
Use the right fields to import a cloud project gateway + add import documentation.
Fixes [#633](https://github.com/ovh/terraform-provider-ovh/issues/633)
> fix: Use the correct fields to import resource ovh_cloud_project_gateway

- ovh/data_me_installation_template.go
- website/docs/d/me_installation_template.html.markdown
fix dedicated_me_installation_template (add inputs attribute & update doc )
```hcl
xx = "yy"
zz = "aa"
}
```
> fix dedicated_me_installation_template (add inputs attribute & updatedoc )

- ovh/data_cloud_project_loadbalancers_test.go
> fix: Ensure we have an available loadbalancer when running TestAccDataSourceCloudProjectBalancers_basic

- ovh/resource_cloud_project_kube_nodepool.go
> fix: kube_nodepool: raise timeout to 1h

- ovh/helpers/helpers.go
Fixes [#653](https://github.com/ovh/terraform-provider-ovh/issues/653)
> fix: Verify type assertions in helper StringsFromSchema

- website/docs/r/cloud_project_kube_nodepool.html.markdown
Updates the default terraform example to remove extraneous managed kubernetes nodepools configuration 
Applied and destroyed the sample configuration
* Terraform version: `terraform version`: Terraform v1.5.6
```hcl
terraform {
required_providers {
ovh = {
source = "ovh/ovh"
source = "terraform.local/local/ovh"
}
}
}
provider "ovh" {
endpoint           = "ovh-eu"
application_key    = "aa"
application_secret = "bb"
consumer_key       = "cc"
}
resource "ovh_cloud_project_kube" "mycluster" {
service_name = "xxx"
name         = "my_kube_cluster"
region       = "GRA11"
}
resource "ovh_cloud_project_kube_nodepool" "pool" {
service_name  = "xxx"
kube_id       = …
```
> fix(docs): remove extra finalizers in example mks configuration

- website/docs/index.html.markdown
Add a link  to the doc that explains how to list/revoke API keys.
> doc: Add a link to the doc to list/revoke API keys

- ovh/resource_dedicated_nasha_partition_access.go
- ovh/resource_dedicated_nasha_test.go
- ovh/types_dedicated_nasha.go
- website/docs/r/dedicated_nasha_partition_access.markdown
> fix: Add acl_description to resource ovh_dedicated_nasha_partition_access

- ovh/resource_cloud_project.go
- ovh/resource_cloud_project_test.go
> fix: Retrieve service information when importing/reading ovh_cloud_project

- ovh/resource_dedicated_server_update.go
- ovh/resource_dedicated_server_update_test.go
- ovh/services.go
- ovh/types_service.go
- website/docs/r/dedicated_server_update.html.markdown
> feat: Allow to update display name of a dedicated server using resource ovh_dedicated_server_update

- ovh/data_dbaas_logs_output_graylog_stream_test.go
- ovh/resource_dbaas_logs_output_graylog_stream_test.go
- website/docs/r/dbaas_logs_output_graylog_stream.html.markdown
> doc: Explain how to define a retention period on resource ovh_dbaas_logs_output_graylog_stream

- ovh/resource_cloud_project_kube.go
- ovh/resource_cloud_project_kube_test.go
Fix schema where requiredWith was inverted
Fixes #683  (issue)
- [x ] Bug fix (non-breaking change which fixes an issue)
> fix(schema): bug 683, fix schema requiredWith

- website/docs/r/cloud_project_network_private_subnet.html.markdown
Typo fix in doc
- [ x] Documentation update
N/A
> Fix typo in cloud_project_network_private_subnet.html.markdown

- ovh/resource_iploadbalancing_udp_farm_gen.go
- ovh/resource_iploadbalancing_udp_farm_server_gen.go
- ovh/resource_iploadbalancing_udp_frontend_gen.go
ovh_iploadbalancing_udp_*: fix definitions
> fix definition of ovh_iploadbalancing_udp_*

- website/docs/r/cloud_project_kube.html.markdown
add  details on `nodes_subnet_id` and `load_balancers_subnet_id` behavior.
- [ X] Documentation update
N/A
> Add network documentation on cloud_project_kube

- ovh/data_cloud_project_database_log_subscription.go
- ovh/data_cloud_project_database_log_subscriptions.go
- ovh/resource_cloud_project_database_log_subscription.go
- ovh/resource_cloud_project_region_loadbalancer_log_subscription.go
- website/docs/d/cloud_project_database_log_subscriptions.html.markdown
- website/docs/r/cloud_project_database_log_subscription.html.markdown
Fixes a typo, `subscrition` => `subscription`
> chore: fix `subscrition` typo

- ovh/order.go
- ovh/resource_ip_service.go
`r/ovh_ip_service` and `order`: retrieve serviceName from the order ID using the correct route in each region.
> fix: Correctly retrieve serviceName from orderId for ip_service in the US

- ovh/resource_dedicated_server_gen.go
Fixes a panic when trying to marshal/merge field `user_metadata`.
> fix: Correctly handle user_metadata in resource ovh_dedicated_server

- website/docs/d/cloud_project_gateway_interface.html.markdown
- website/docs/d/cloud_project_network_private_subnets.html.markdown
- website/docs/d/cloud_project_network_privates.html.markdown
- website/docs/d/cloud_project_region_loadbalancer_log_subscription.markdown
- website/docs/d/cloud_project_region_loadbalancer_log_subscriptions.markdown
- website/docs/r/cloud_project_gateway.html.markdown
- website/docs/r/cloud_project_gateway_interface.html.markdown
- website/docs/r/cloud_project_region_loadbalancer_log_subscription.markdown
> chore: reorganize docs

- ovh/data_dedicated_server.go
- ovh/data_dedicated_server_test.go
- ovh/types_dedicated_server.go
- website/docs/d/dedicated_server.html.markdown
> fix: Add missing fields in datasource ovh_dedicated_server

- .cds/terraform-provider-ovh.pip.yml
- ovh/resource_savings_plan.go
- website/docs/r/savings_plan.html.markdown
Add an array of accepted values for the field `flavor` in resource `ovh_savings_plan`.
> fix: Add a list of accepted flavors for resource ovh_savings_plan

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/report-a-bug.md
chore: github: update issue template to remove GPG public key mention
> chore: github: update issue template to remove GPG public key mention

- ovh/resource_cloud_project_region_network_gen.go
- website/docs/r/cloud_project_region_network.html.markdown
> fix: Correct doc for ovh_cloud_project_region_network + fix state merging

- ovh/resource_cloud_project_instance.go
- ovh/resource_cloud_project_instance_test.go
- ovh/resource_cloud_project_loadbalancer.go
- ovh/resource_cloud_project_region_network.go
- ovh/types_cloud.go
- ovh/types_cloud_project_instance.go
Fixes #841  (issue)
Related to #853  (issue)
> fix: Correctly handle SSH keys in ovh_cloud_project_instance resource

- ovh/resource_ip_move.go
- website/docs/r/ip_move.html.markdown
> fix: ovh_ip_move: Fix import and add doc

- ovh/resource_cloud_project_kube.go
> fix: ovh_cloud_project_kube: Increase update timeout

- website/docs/d/cloud_project_loadbalancer_flavors.html.markdown
Change the category for the flavors datasource.
> [Documentation] Change category for Octavia LB

- website/docs/d/cloud_project_rancher.html.markdown
- website/docs/d/cloud_project_rancher_plan.html.markdown
- website/docs/d/cloud_project_rancher_version.html.markdown
- website/docs/r/cloud_project_rancher.html.markdown
> [Documentation] Improve Rancher doc

- ovh/data_cloud_project_rancher_test.go
- ovh/resource_cloud_project_rancher.go
Just small linter fixes & a test fix for the Managed Rancher provider.
> fix(rancher): Small fixes to fix IDE warnings & make tests viable in the long-term

- README.md
Add visual badges in README file including the downloads statistics per month
> Add new visual badges on README file

- ovh/resource_domain_name_gen.go
> fix(ovh_domain_name): Add PlanModifiers to avoid unnecessary diff when target_spec is not set

- docs/data-sources/cloud_project_region.md
- ovh/data_cloud_project_region.go
- ovh/data_cloud_project_region_test.go
- ovh/types_cloud.go
- templates/data-sources/cloud_project_region.md.tmpl
Add missing fields to datasource `ovh_cloud_project_region`.
Fixes #913 (issue)
> feat: Add missing fields to datasource ovh_cloud_project_region

- .cds/terraform-provider-ovh.pip.yml
- .cds/terraform-provider-ovh.yml
- ovh/resource_domain_zone_dynhost_login_test.go
- ovh/resource_domain_zone_dynhost_record_test.go
- Run tests for Storage EFS in CI
- Fix test sweepers for domain/zone/dynhost
> fix: Add missing CI pipeline for EFS + fix DynHost tests

- ovh/order_cart.go
While investigations on failing calls are driven, retrying calls on `order_cart_product` data
Fixes #995 (issue)
> feat(order_cart_product_plan): temporary retries on failing calls

- docs/resources/me_identity_group.md
- templates/resources/me_identity_group.md.tmpl
Added missing documentation for importing me_identity_group resource.
> docs: Add import section to me_identity_group documentation

- docs/resources/cloud_project_containerregistry_user.md
- ovh/resource_cloud_project_containerregistry_user.go
- templates/resources/cloud_project_containerregistry_user.md.tmpl
> doc: Fix doc of ovh_cloud_project_containerregistry_user

- ovh/resource_cloud_project_containerregistry_oidc.go
Force recreation of resource `ovh_cloud_project_containerregistry_oidc` when we get a 404 at read time.
Fixes #1041 (issue)
> fix(ovh_cloud_project_containerregistry_oidc): Recreate OIDC config when removed outside Terraform

- docs/resources/cloud_project_user.md
- templates/resources/cloud_project_user.md.tmpl
Fixes #1074 
Confirmed by Public Cloud team
> chore: documentation: cloud_project_user: update role list

- ovh/resource_cloud_project_region.go
- ovh/resource_cloud_project_region_gen.go
Add an ID field to resource `ovh_cloud_project_region`.
> fix(ovh_cloud_project_region): Add an ID

- .cds/terraform-provider-ovh.yml
- ovh/data_ip_firewall_rule_test.go
- ovh/data_ip_firewall_test.go
- ovh/resource_cloud_project_loadbalancer_test.go
- ovh/resource_cloud_project_network_private_subnet.go
- ovh/resource_cloud_project_region_loadbalancer_log_subscription.go
- ovh/resource_dbaas_logs_input_test.go
- ovh/resource_dbaas_logs_token_test.go
- ovh/resource_ip_firewall.go
- ovh/resource_ip_firewall_rule_test.go
- ovh/resource_ip_firewall_test.go
- ovh/resource_ip_reverse_test.go
This PR fixes several acceptance tests (missing resources cleaning, hardcoded vlan IDs, wrongly grouped tests, ...).
> fix acceptance tests

- docs/resources/vps.md
- examples/resources/vps/example_1.tf
- ovh/resource_vps.go
- ovh/resource_vps_gen.go
- templates/resources/vps.md.tmpl
> fix: ovh_vps: make sure resource is saved in state before performing rebuild that can fails
