ovh/terraform-provider-ovh

ovh/data_source_ovh_publiccloud_region.go

Related to https://github.com/hashicorp/terraform/pull/15562
This is a first step prior to bumping vendored `hashicorp/terraform` to `v0.10.0`.

d/ovh_publiccloud_region: Deprecate non compliant fields

---

website/docs/r/publiccloud_private_network.html.markdown

`publiccloud_private_network` should refer to `vlan_id` rather than `vland_id`.

Docs: minor typo fix

---

website/docs/r/vrack_publiccloud_attachment.html.markdown

`vrack_publiccloud_attachment`'s `project_id` defaults to `OVH_PROJECT_ID`, not `OVH_VRACK_ID`.

Docs: fix copy/paste error

---

ovh/provider.go
ovh/provider_test.go
ovh/resource_ovh_dns_record.go
ovh/resource_ovh_dns_record_test.go
website/docs/index.html.markdown
website/docs/r/ovh_domain_zone_record.html.markdown

Hello @yanndegat 
As you ask in the previous pr https://github.com/hashicorp/terraform/pull/14775
i moved my pr in this project,
here is my little readme again so we can continue to review my pr here 
howto
if you want to use the OVH API you have to generate:
An Application Key
An Application Secret Key
A Consumer Key
you can generate all three on this page
https://eu.api.ovh.com/createToken/
the following rights are needed for this plugin
GET : /domain/zone/*
PUT : /domain/zone/*
POST : /domain/zone/*
DELETE : /domain/zone/*
GET : /me
ovh.tf example
provider "ovh" {
application_key = "azrzqrgqvvdsfgsfffgc"
application_secret = "aztfqsqfsdcsdqezrfdvcx"
consumer_key = "aergfvdsrgtfbvcretfgd"
}
resource "ovh_domain_zone_record" "test" {
zone = "testdemo.ovh"
subDomain = "test"
fieldType = …

R ovh domains zone

---

ovh/provider.go

Read the environment variable $HOME when user.Current() fails
which is what happens when the cross compilation is enabled
(that is, without cgo).
Fixes #15

Fallback to get current home directory

---

ovh/provider.go
ovh/resource_ovh_domain_zone_redirection.go
ovh/resource_ovh_domain_zone_redirection_test.go
website/docs/r/ovh_domain_zone_redirection.html.markdown
website/ovh.erb

Feat: implement domain zone redirection

---

ovh/helpers.go
ovh/provider.go
ovh/resource_ovh_iploadbalancing_tcp_farm_server.go
ovh/resource_ovh_iploadbalancing_tcp_farm_server_test.go
website/docs/r/iploadbalancing_tcp_farm_server.markdown

This commit introduces `ovh_iploadbalancing_tcp_farm_server`.

adds ovh_iploadbalancing_tcp_farm_server resource

---

ovh/data_source_ovh_bankaccount.go
ovh/data_source_ovh_creditcard.go
ovh/provider.go

In order to make payment for vps resource creation or any other kind of classic (non cloud) ovh products a data source for payments method would make things easier.
I've a question regarding tests, if I use two env variable with filter patterns for credit card or bank account and check there is a match, is it enough ?

Payment data sources

---

ovh/helpers.go
ovh/provider.go
ovh/resource_ovh_iploadbalancing_http_route.go
ovh/resource_ovh_iploadbalancing_http_route_rule.go
ovh/resource_ovh_iploadbalancing_http_route_rule_test.go
ovh/resource_ovh_iploadbalancing_http_route_test.go
website/docs/r/resource_ovh_iploadbalancing_http_route.markdown
website/docs/r/resource_ovh_iploadbalancing_http_route_rule.markdown

Sorry OVH related doc is only in french ... https://docs.ovh.com/fr/load-balancer/routes/

Add ovh_iploadbalancing_http_route resource

---

ovh/data_source_ovh_me_paymentmean_bankaccount.go
ovh/data_source_ovh_me_paymentmean_bankaccount_test.go
ovh/data_source_ovh_me_paymentmean_creditcard.go
ovh/data_source_ovh_me_paymentmean_creditcard_test.go
ovh/provider.go

- d/ovh_bank_account > d/ovh_me_paymentmean_bankaccount
- d/ovh_credit_card > d/ovh_me_paymentmean_creditcard
- add optional acc test for payment means

Refactor paymentmeans to reflect convention

---

ovh/resource_ovh_domain_zone_record.go
website/docs/r/ovh_domain_zone_record.html.markdown

Previsous PR was not working due to the fact that id without zone do not define a record. This PR works this around by importing using OVH_ID.zone format as explained in the updated documentation

Use zone in ID to get import working and write doc

---

ovh/provider.go

This will _actually_ deprecate data sources and resources which were part of #31 
This makes Terraform show warnings when such deprecated data source or resource is in the config.
e.g.
```
$ terraform apply
data.ovh_publiccloud_regions.regions: Refreshing state...
Warning: Use ovh_cloud_regions data source instead
on main.tf line 5, in data "ovh_publiccloud_regions" "regions":
5: data "ovh_publiccloud_regions" "regions" {
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Deprecate publiccloud data sources & resources

---

go.mod
ovh/provider.go

This PR building on top of #10 and uses `go-homedir` which has more robust mechanism (which doesn't _just_ rely on `os/user` & single ENV variable) to detect user's home directory across platforms.

provider: Make homedir detection more robust

---

ovh/resource_ovh_domain_zone_record.go
ovh/resource_ovh_domain_zone_record_test.go

Tests without patch:
```
make testacc TEST=./ovh TESTARGS='-run=TestAccOvhDomainZoneRecord_updateType'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./ovh -v -run=TestAccOvhDomainZoneRecord_updateType -timeout 120m
=== RUN   TestAccOvhDomainZoneRecord_updateType
--- FAIL: TestAccOvhDomainZoneRecord_updateType (12.17s)
testing.go:538: Step 1 error: Error applying: 1 error(s) occurred:
* ovh_domain_zone_record.foobar: 1 error(s) occurred:
* ovh_domain_zone_record.foobar: Failed to update OVH Record: Error 400: "Try to alter read-only properties: fieldType"
FAIL
FAIL	github.com/terraform-providers/terraform-provider-ovh/ovh	12.194s
make: *** [testacc] Error 1
```
with patch:
```
make testacc TEST=./ovh TESTARGS='-run=TestAccOvhDomainZoneRecord_updateType'
==> …
```

ovh_domain_zone_record: Make fieldtype non-updatable

---

website/ovh.erb

The documentation page for `ovh_iploadbalancing_refresh` exists but is not linked in the sidebar.

Add "ovh_iploadbalancing_refresh" to the website sidebar

---

go.sum
ovh/data_source_ovh_domain_zone_test.go
ovh/data_source_ovh_iploadbalancing_test.go
ovh/data_source_ovh_me_paymentmean_bankaccount_test.go
ovh/data_source_ovh_me_paymentmean_creditcard_test.go
ovh/data_source_ovh_publiccloud_region_test.go
ovh/data_source_ovh_publiccloud_regions_test.go
ovh/provider_test.go
ovh/resource_ovh_domain_zone_record_test.go
ovh/resource_ovh_domain_zone_redirection_test.go
ovh/resource_ovh_ip_reverse_test.go
ovh/resource_ovh_iploadbalancing_http_farm_server_test.go
ovh/resource_ovh_iploadbalancing_http_farm_test.go
ovh/resource_ovh_iploadbalancing_http_route_rule_test.go
ovh/resource_ovh_iploadbalancing_http_route_test.go
ovh/resource_ovh_iploadbalancing_tcp_farm_server_test.go
ovh/resource_ovh_iploadbalancing_tcp_frontend_test.go
ovh/resource_ovh_publiccloud_private_network_subnet_test.go
ovh/resource_ovh_publiccloud_private_network_test.go
ovh/resource_ovh_publiccloud_user_test.go
ovh/resource_ovh_vrack_publiccloud_attachment_test.go

In order to more easily run tests selectively, I split all the pre check
tests. This way you don't need all the OVH_* env variables when testing
only a part of the provider.

Split PreCheck for acceptance tests

---

ovh/resource_ovh_domain_zone_record.go
ovh/resource_ovh_domain_zone_record_test.go

The OvhDomainZoneRecordImportState can have an Id bigger than 32 bits.
I did this temporary fix for my own use, and created the pull request to open the conversation.
I'm not a Go developer and just made this to continue working.

handle record id bigger than 32bits

---

ovh/resource_ovh_publiccloud_private_network_subnet_test.go
ovh/resource_ovh_publiccloud_private_network_test.go

- fix acctest: since new global regions are returned
by the ovh_cloud_regions datasource, filter regions
with network service UP
- use OVH_ATTACH_VRACK=0 env var to disable vrack_attach
(useful when running tests against a project already
attachted to a project)
- rework test with more terraform-sdk test helper funcs

r/cloud_network_private/subnet: fix acctest & rework

---

ovh/resource_ovh_iploadbalancing_http_farm.go
website/docs/r/iploadbalancing_http_farm.markdown

Control value for stickiness on the ressource ovh_iploadbalancing_http_farm doesn't allow to use cookie.

add cookie to http farm stickiness

---

ovh/data_source_ovh_vps.go
ovh/data_source_ovh_vps_test.go
ovh/provider.go
ovh/provider_test.go
ovh/types_vps.go
website/docs/d/vps.html.markdown

This is the first step to have feature parity between vps and dedicated servers.

Add a datasource for vps (on the dedicated_server model)

---

.goreleaser.yml

Generate FreeBSD binaries, as in default goreleaser.yml:
https://github.com/hashicorp/terraform-provider-scaffolding/blob/master/.goreleaser.yml

Add FreeBSD support

---

website/docs/index.html.markdown

Based on my difficulties to use the OVH provider I proposed some improvements to the readme on Terraform registry. It solves issue #161 and #9.
I describe how to retrieve the API keys and re-ordered the description about its use in the configuration.
Note that the english speaking documentation (the only one I found via Google) do barely help. The French speaking one is much better.
I wonder if there shouldn't be a hint to use the `Use Provider` button to generate the `required providers` block. Newcomers might not be familiar with the use non-official providers.

Improve readme (generation of keys)

---

website/docs/r/cloud_project_kube_nodepool.html.markdown

I noticed a small typo in k8s nodepool documentation.

Fix typo in nodepool documentation

---

ovh/resource_cloud_project_user.go

This follows the service_name/id format if OVH_CLOUD_PROJECT_SERVICE
is not set.

r/cloud_project_user: Add an importer

---

ovh/types_dbaas_logs_input.go
ovh/types_me.go
ovh/types_order_cart_item.go

Fixes these types of warnings:
struct field tag `json:createdAt` not compatible with reflect.StructTag.Get: bad syntax for struct tag value

fix: use the right json annotation

---

ovh/resource_domain_zone_record.go

r/domain_zone_record: fix panic when del. outside tf

---

ovh/resource_cloud_project_kube.go

the ResourceImporter references the NodePool import method `resourceCloudProjectKubeNodePoolImportState` instead of `resourceCloudProjectKubeImportState`

fix(resource_cloud_project_kube): correct the import method

---

website/docs/r/cloud_project_kube.html.markdown

Hey there :vulcan_salute:
this PR adds the missing `id` attribute. I stumbled on this while creating a node pool, that needs the `kube_id` as an argument.
Kind regards
Florian

Add missing `id` attribute

---

website/docs/index.html.markdown

In terraform CLI version 0.12 and earlier, and 0.13 and later the provider configuration way are not the same

feat: improve the provider configuration and init for TF version 0.13 and 0.12

---

ovh/resource_dbaas_logs_output_graylog_stream.go

This PR fixes a typo in the `cold_storage_content` parameter for the `ovh_dbaas_logs_output_graylog_stream` resources

Fix typos in allowed logs output format

---

ovh/resource_cloud_project_network_private.go

Close https://github.com/ovh/terraform-provider-ovh/issues/253
This fix propose to switch `regions_attributes` to `Set` to follow API behavior. 
Underlying [OVH API](https://api.ovh.com/console/#/cloud/project/{serviceName}/network/private/{networkId}~GET) returns unordered networks and trigger terraform changes during plan/apply :
```
HTTP/1.1 200 OK
{
"id": "pn-xxxxxx_43",
"name": "private-network",
"vlanId": 43,
"regions": [
{
"region": "GRA7",
"status": "ACTIVE",
"openstackId": "********-****-****-****-************"
},
{
"region": "SBG5",
"status": "ACTIVE",
"openstackId": "********-****-****-****-************"
},
{
"region": "GRA5",
"status": "ACTIVE",
"openstackId": "********-****-****-****-************"
},
{
"region": "GRA9",
"status": "ACTIVE",
"openstackId": …
```

Fix ordering issue with private networks

---

ovh/data_cloud_project_user_s3_credential.go
ovh/data_cloud_project_user_s3_credential_test.go
ovh/data_cloud_project_user_s3_credentials.go
ovh/data_cloud_project_user_s3_credentials_test.go
ovh/provider.go
ovh/resource_cloud_project_user_s3_credential.go
ovh/resource_cloud_project_user_s3_credential_test.go
ovh/types_cloud.go
website/docs/d/cloud_project_user_s3_credential.html.markdown
website/docs/d/cloud_project_user_s3_credentials.html.markdown
website/docs/r/cloud_project_user_s3_credential.html.markdown
website/ovh.erb

Add the datasources and resource to create and retrieve S3 Credentials (AccessKeyId and SecretAccessKey) required to access S3 buckets. Fixes #285

Add S3 Credential datasource and resource

---

ovh/helpers/helpers.go
ovh/resource_cloud_project_network_private.go
ovh/resource_cloud_project_network_private_helpers.go

With this fix is resolved the #281

fix: add hashing function on region attributes

---

ovh/resource_cloud_project_kube.go
ovh/resource_cloud_project_kube_test.go
website/docs/r/cloud_project_kube.html.markdown

optional update_policy parameter at cluster creation, APIV6 was updated 
no exception thrown at cluster creation when specifying the update_policy parameter

Kube: optional update_policy parameter at cluster creation

---

ovh/order.go

Sometimes the order API takes too long to send the confirmation email after calling `.../terminate` on a product.
This email contains the token needed to call `.../confirmTermination`.
The PR increases the timeout of waiting for that email to show up in `/me/notifications/email/history`

Extend order termination timeout to 30minutes

---

ovh/helpers/helpers.go

The is a fix to the creation of iplb frontend ressources
Since the 0.19.0 version the creation fail as the provider will always set a value for `default_ssl_id` and `default_farm_id` params
The bug was introduce in this commit: [50d254d2ade1](https://github.com/ovh/terraform-provider-ovh/commit/50d254d2ade1022383805293689430e174ed269a#diff-ee495b1dc0a50f4b42ae2b3b09e6f4d2cf9213f3acacba6c5ffc3be37b964cc6
) 
I simply revert the change made to the helper
But I can't test the other implications change or why this change was made in the first place

fix: iplb frontend default values

---

ovh/resource_cloud_project_kube_test.go

Fix acceptance test.
We now need to make a `tolist(...)`in order to retrieve the `private_network_id`.

fix: schema have been modified so tolist is now required

---

ovh/resource_cloud_project_kube.go
ovh/resource_cloud_project_kube_test.go

the library harshicorp go-version did not change of version but return 3 segments even if there is only 2

fix harshicorp go-version library usage && acceptance test

---

ovh/resource_dedicated_server_install_task.go

Hi,
We implement the bootid_on_destroy when we create the dedicated_server installation task but we do not use it when destroying the resource.
This pr aims to fix that.
Signed-off-by: Arnaud SINAYS <sinaysarnaud@gmail.com>

dedicated_server: update bootid before reboot on destroy

---

website/docs/r/cloud_project_network_private.html.markdown
website/docs/r/cloud_project_network_private_subnet.html.markdown
website/docs/r/vrack_cloudproject.markdown

Litle contribution to improve Terraform's provider documentation.

cloud_project_network_private and cloud_project_network_private_subnet

---

ovh/resource_cloud_project_kube_nodepool.go
ovh/resource_cloud_project_kube_nodepool_test.go

the 25th of october, a change will be prodded to replace node pool RESIZING status to DOWNSCALING and UPSCALING status.
pending state change has to be adapt
NOTA: when running test do not forget to raise go test timeout with "-timeout 30m"

replace resizing status to upscaling/downscaling

---

.goreleaser.yml
go.mod
go.sum
ovh/config.go
vendor/github.com/ovh/go-ovh/ovh/error.go
vendor/github.com/ovh/go-ovh/ovh/ovh.go
vendor/modules.txt

Since most of Terraform providers are customising the User-Agent to detect the calls that comes from Terraform usage, we should do the same on the terraform-provider-ovh.
It will include the Terraform provider version, that will ease the debugging purpose when customers comes to us with problems.

feat(go-ovh): add User-Agent on go-ovh client to identify calls that comes from Terraform

---

ovh/resource_vrack_dedicated_server.go
website/docs/r/dedicated_server_install_task.html.markdown
website/docs/r/dedicated_server_reboot_task.html.markdown
website/docs/r/dedicated_server_update.html.markdown
website/docs/r/vrack_dedicated_server.html.markdown
website/docs/r/vrack_dedicated_server_interface.html.markdown

This PR is following this one: #323 that has been reverted.
* Followed https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations#provider-data-source-or-resource-removal and added a `DeprecationMessage` to the resource schema definition.
* Changed the documentation to highlight the deprecation if favor of `ovh_vrack_dedicated_server_interface`.
* And some minor documentation fixes.

deprecate resource_vrack_dedicated_server 

---

ovh/provider.go
ovh/resource_cloud_project_region_storage_presign.go
ovh/resource_cloud_project_region_storage_presign_test.go
ovh/types_presigned_url.go
website/docs/r/cloud_project_region_storage_presign.html.markdown
website/ovh.erb

Use this resource to presign url to interact with s3 fast storage.
This can be used for multiple uses-cases like uploading a post-install script to s3 then passing the URL to a dedicated_server install task. The URL is signed for a fixed period, hence the `expire` parameter.
Signed-off-by: Arnaud SINAYS <sinaysarnaud@gmail.com>

feat(ovh_cloud_project_region_storage_presign): add resource

---

.gitignore
ovh/provider.go
ovh/resource_dedicated_server_networking.go
ovh/resource_dedicated_server_networking_test.go
ovh/types_dedicated_server_networking.go
website/docs/index.html.markdown
website/docs/r/ovh_dedicated_server_networking.html.markdown

Tested with my account
```
❯ make testacc TESTARGS="-run TestAccresourceDedicatedServerNetworking"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccresourceDedicatedServerNetworking -timeout 240m
?       github.com/ovh/terraform-provider-ovh   [no test files]
=== RUN   TestAccresourceDedicatedServerNetworking
--- PASS: TestAccresourceDedicatedServerNetworking (3468.55s)
PASS
ok      github.com/ovh/terraform-provider-ovh/ovh       3468.986s
?       github.com/ovh/terraform-provider-ovh/ovh/helpers       [no test files]
testing: warning: no tests to run
PASS
ok      github.com/ovh/terraform-provider-ovh/ovh/helpers/hashcode      (cached) [no tests to run]
```

Add resource dedicated_server_networking

---

ovh/resource_ip_reverse.go
website/docs/r/ip_reverse.html.markdown

When importing an `ovh_ip_reverse` resources, the user is expected to
provide the IP block and IP address separated with a colon, e.g.
`198.51.100.0/24:198.51.100.42`:
* `198.51.100.0/24` is extracted as the IP block;
* `198.51.100.42` is extracted as the address.
Unfortunately, the `:` separator does not work well with IPv6 addresses,
e.g. `2001:0DB8::/32:2001:0DB8::42` is interpreted as:
* `2001` is extracted as the IP block;
* `0DB8::/32:2001:0DB8::42` is extracted as the address.
This is obviously wrong and raise an API error:
```
│ Error: calling /ip/%222001/reverse/0DB8::%2F32:2001:0DB8::42:
│ 	 HTTP Error 400: "[ipReverse] Given data (0DB8::/32:2001:0DB8::42) is not valid for type ip"
```
Replace the `:` separator with a `|` separator to avoid this issue.

Fix import of ovh_ip_reverse resources with IPv6

---

ovh/resource_iploadbalancing_http_frontend.go
ovh/resource_iploadbalancing_http_frontend_test.go
ovh/types_iploadbalancing.go
website/docs/r/iploadbalancing_http_frontend.html.markdown

This commit adds support for `httpHeader` attribute when manipulating http frontend.
See: https://docs.ovh.com/fr/load-balancer/http-headers

Add support for HTTP header on resource_iploadbalancing_http_frontend

---

website/docs/d/vpss.html.markdown

So I am not an expert in terraform but I think you are missing the prefix here.

typo: missing prefix

---

ovh/resource_iploadbalancing_http_frontend.go
ovh/resource_iploadbalancing_http_frontend_test.go
ovh/types_iploadbalancing.go
website/docs/r/iploadbalancing_http_frontend.html.markdown

Hey! This PR aims to add a missing parameter on `iplb_http_frontends`.
Signed-off-by: tanguy.desreumaux <tanguy.desreumaux@ovhcloud.com>

feat(loadbalancing): add hsts option to http frontend

---

ovh/resource_cloud_project_kube.go
ovh/resource_cloud_project_kube_iprestrictions.go
ovh/resource_cloud_project_kube_nodepool.go
ovh/resource_cloud_project_kube_oidc.go
website/docs/r/cloud_project_kube.html.markdown
website/docs/r/cloud_project_kube_iprestrictions.html.markdown
website/docs/r/cloud_project_kube_nodepool.html.markdown
website/docs/r/cloud_project_kube_oidc.html.markdown

Use user-provided timeouts for all resources

---

ovh/data_dbaas_logs_input_engine_test.go
ovh/provider_test.go
ovh/resource_dbaas_logs_input_test.go
website/docs/index.html.markdown

ref: #OB-4901
Hello,
This PR fix a missing parameter (serviceName) on tests to handle the new endpoint as described here: https://github.com/ovh/terraform-provider-ovh/pull/347
As always, thanks for your time on this.
Signed-off-by: Pierre De Paepe <pierre.de-paepe@ovhcloud.com>

fix(dbaas-logs): input tests

---

ovh/data_cloud_project_kube.go
ovh/data_cloud_project_kube_test.go
ovh/resource_cloud_project_kube.go
ovh/resource_cloud_project_kube_nodepool.go
ovh/resource_cloud_project_kube_test.go
ovh/types_cloud_project_kube.go
ovh/types_cloud_project_kube_test.go
website/docs/d/cloud_project_kube.html.markdown
website/docs/r/cloud_project_kube.html.markdown

- Added a new argument in resource `ovh_cloud_project_kube` called `customization_kube_proxy` to customize whether to use `iptabes` or `ipvs` and related settings
- Add a new argument `kube_proxy_mode` to choose between `iptables` or `ipvs`
- TypeSet `customization.apiserver` is now `customization_apiserver`

feat(kube): Let user configure kube proxy

---

ovh/data_cloud_project_kube.go
ovh/data_cloud_project_kube_test.go
ovh/helpers/helpers.go
ovh/resource_cloud_project_kube.go
ovh/resource_cloud_project_kube_nodepool.go
ovh/resource_cloud_project_kube_test.go
ovh/types_cloud_project_kube.go
ovh/types_cloud_project_kube_test.go
website/docs/d/cloud_project_kube.html.markdown
website/docs/r/cloud_project_kube.html.markdown

- Added a new argument in resource `ovh_cloud_project_kube` called `customization_kube_proxy` to customize whether to use `iptabes` or `ipvs` and related settings
- Add a new argument `kube_proxy_mode` to choose between `iptables` or `ipvs`
- TypeSet `customization.apiserver` is now deprecated in favor of `customization_apiserver`
- fix(kube): Detect change on old customization attribute
- fix(kube): Support old and new apiserver customization
- fix(kube): User timeout was not used when waiting for cluster to be ready

Let user configure kube proxy

---

website/docs/r/cloud_project_workflow_backup.html.markdown

Name of the resource was wrong 
- [ x] Documentation update
N/A
N/A

Fix workflow backup resource name that was wrong in the doc page

---

website/docs/r/me_installation_template_partition_scheme_partition.html.markdown

Describe the enum values for attributes filesystem, raid and type for resource ovh_me_installation_template_partition_scheme_partition
Related to #377 
- [ X] Documentation update
N/A
N/A

Add enum description for attributes in ovh_me_installation_template_partition_scheme_partition

---

ovh/resource_ip_reverse_test.go
website/docs/r/ip_reverse.html.markdown

Separator for import have been updated from `:` to `|` 
However the test TestAccIpReverse_importBasic was still using `:` so was failing
Related to #380  
- [ x] (Test) Bug fix (non-breaking change which fixes an issue)

Update separator for  ip reverse import test 

---

website/docs/r/ovh_domain_zone_record.html.markdown

It should be an int but example can be misleading.
Updating example inside documentation for ttl value in ovh_domain_zone_record.
- Documentation update

fix(docs) ovh_domain_zone_record: remove quote for ttl value in example

---

website/docs/r/cloud_project_kube.html.markdown

The certificate attributes of the kubeconfig are base64 encoded. Therefore you can't use them as is with the Helm provider and you need to base64 decode them before use.

fix(doc) Add base64 decode

---

ovh/resource_domain_zone_record.go
ovh/resource_domain_zone_record_test.go
website/docs/r/ovh_domain_zone_record.html.markdown

the zone record route sets the TTL to 60 (and return 200) even if the request contains a value below. This cause terraform to update the record at each `apply`.
This patch validates that the TTL set by the user in his script is >= to 60.
- [x ] Bug fix (non-breaking change which fixes an issue)
This will be a breaking for user that set TTL to a value below 60. However, in that case, their value is not set since the server set the value to 60 
- [X ] Test A: `make testacc TESTARGS="-run TestAccDomainZoneRecord_Basic"`
- [x ] My code follows the style guidelines of this project …

Validate TTL in zone_record to >=60

---

website/docs/r/ovh_domain_zone_record.html.markdown

Related to #275 
Add some documentation on a bulk record update feature in the web console that update the ids of the records leading to error in terraform afterwards
- [x ] Documentation update
N/A

[DNS Record] add warning on `Change in text format` feature from the web console

---

ovh/data_cloud_project_database_user.go
ovh/data_cloud_project_database_user_test.go
ovh/data_cloud_project_database_users_test.go
ovh/resource_cloud_project_database_user.go
ovh/resource_cloud_project_database_user_test.go
ovh/types_cloud_project_database.go
website/docs/d/cloud_project_database_user.html.markdown
website/docs/r/cloud_project_database_user.html.markdown

Manage grafana in the generic database user resources.
Grafana do not allow to create user but now you can map the already created "avnadmin" user with a resource to reset it password
Fixes #407 
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- `make testacc TESTARGS="-run TestAccCloudProjectDatabaseUser_basic"`
- `make testacc TESTARGS="-run TestAccCloudProjectDatabaseUserDataSource_basic"`
- `make testacc TESTARGS="-run TestAccCloudProjectDatabaseUsersDataSource_basic"`

add grafana user

---

website/docs/index.html.markdown

Add documentation on multiple providers usage
Remove redundant information (keys in dev section) 
- [ x] Documentation update
N/A
N/A

Add documentation on multiple providers usage

---

CONTRIBUTING.md
ovh/data_order_cart.go
website/docs/d/order_cart.html.markdown

Correct typos in `ovh/data_order_cart.go`, `website/docs/order_cart.html.markdown` and `CONTRIBUTING.md`

---

website/docs/d/dedicated_server.html.markdown

Fix a typo in documentation
```hcl
xx = "yy"
zz = "aa"
}
```

Fix typo on attribute name

---

.cds/terraform-provider-ovh.yml
ovh/resource_cloud_project_database.go
ovh/resource_cloud_project_database_integration.go
ovh/resource_cloud_project_database_kafka_topic.go
ovh/resource_cloud_project_database_m3db_namespace.go
ovh/resource_cloud_project_database_redis_user.go

To avoir Conflict error on Kafka Topic, I add a retry logic on this resource
-  `make testacc TESTARGS="-run TestAccCloudProjectDatabaseKafkaTopic_basic"`

add retry on kafka topic + clean dead code

---

ovh/resource_iploadbalancing_http_farm_server_test.go
ovh/resource_iploadbalancing_tcp_farm_server_test.go

Removing the introduced test in #428, it turns out the whole API response is written inside the resource. Including the null values. Which means the TestCheckNoResourceAttr was not fitting. Not replacing it as there's no built-in func that allows for checking that a resource is set while having a nil value.

fixes bug in TestAcc for iploadbalancing http/tcp server

---

ovh/resource_dedicated_server_install_task.go
website/docs/r/dedicated_server_install_task.html.markdown

Improves error handling when creating a dedicated server install task by allowing the POST to fail and be retried.
Adds import on ovh_dedicated_server_install_task resource
Import has been tested using the following configuration:
```hcl
resource "ovh_dedicated_server_install_task" "test" {
service_name = "nsXXXX.ip-XXXX.net"
template_name = "my_custom_template"
}
```
And using the following command to import the task:
```shell
terraform import ovh_dedicated_server_install_task.test nsXXXX.ip-XXXX.net/my_custom_template/YYYYYY
```

improvement: allow retry on install task creation and add import

---

ovh/resource_me_identity_user.go
ovh/resource_me_identity_user_test.go
ovh/types_me.go

A typo in the resource_me_identity resource implementation prevented user update. This PR fixes the typo and other errors rising from the fix.
Fixes  #441

fix: resource_me_identity update

---

ovh/resource_me_installation_template_test.go

The useDistribKernel flag was deprecated (i.e. not used) by the backend 3 years ago. However it was still to possible to set / get this value. This is not anymore the case, breaking the CI test.

Fix resource_me_installation_template_test 

---

ovh/provider_test.go
ovh/resource_dedicated_server_networking_test.go
website/docs/r/ovh_dedicated_server_networking.html.markdown

Improvement in the management of the specificities of dedicated_serve…r_networking which is an `Internal` route that shall be authorized manually.
- Doc update to state that this is not a 'normal' resource
- Add a specific env variable in order to run the tests : this enables a user that is not authorized to call this route to skip the test easily
- [ x] Improvement (improve existing resource(s) or datasource(s))
- [ x] Documentation update

dedicated_server_networking specificities improvement

---

ovh/data_cloud_project_database_kafka_schemaregistryacl.go
ovh/data_cloud_project_database_kafka_schemaregistryacls.go
ovh/data_cloud_project_database_kafka_schemaregistryacls_test.go
ovh/import_cloud_project_database_kafka_schemaregistryacl_test.go
ovh/provider.go
ovh/resource_cloud_project_database_kafka_schemaregistryacl.go
ovh/resource_cloud_project_database_kafka_schemaregistryacl_test.go
ovh/types_cloud_project_database.go

Fixes Kafka schema registry data source test
Add Kafka schema registry import test

Fix kafka schema registry tests add import test

---

ovh/provider_test.go
ovh/resource_iploadbalancing_http_frontend.go
ovh/resource_iploadbalancing_http_frontend_test.go
website/docs/index.html.markdown

- Update `dedicated_ipfo` attribute to TypeSet
- Update http frontend test to add failover IP attributes
Fixes #439 
- [X ] My code follows the style guidelines of this project
- [X ] I have performed a self-review of my code
- [X ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings or issues
- [ X] I have added acceptance tests that prove my fix is effective or that my feature works
- [ X] New and existing acceptance tests pass locally with my changes
- [X ] I ran succesfully `go mod vendor` if I added or modify `go.mod` file

Solve issue 439

---

website/docs/r/cloud_project_kube.html.markdown

Just a typo fix `ouput` > `output`

typo: Update cloud_project_kube.html.markdown

---

ovh/data_cloud_project_capabilities_containerregistry_filter_test.go
ovh/data_cloud_project_capabilities_containerregistry_test.go
ovh/data_cloud_project_containerregistry_oidc.go
ovh/data_cloud_project_containerregistry_oidc_test.go
ovh/data_cloud_project_containerregistry_test.go
ovh/data_cloud_project_containerregistry_users_test.go
ovh/provider.go
ovh/provider_test.go
ovh/resource_cloud_project_containerregistry_oidc.go
ovh/resource_cloud_project_containerregistry_oidc_test.go
ovh/resource_cloud_project_containerregistry_test.go
ovh/resource_cloud_project_containerregistry_user_test.go
ovh/types_cloud_project_containerregistry_oidc.go
website/docs/d/cloud_project_containerregistry.html.markdown
website/docs/d/cloud_project_containerregistry_oidc.html.markdown
website/docs/d/cloud_project_containerregistry_users.html.markdown
website/docs/index.html.markdown
website/docs/r/cloud_project_containerregistry.html.markdown
website/docs/r/cloud_project_containerregistry_oidc.html.markdown
website/docs/r/cloud_project_containerregistry_user.html.markdown

Add Managed Private Registry OIDC configuration (relative to https://github.com/ovh/public-cloud-roadmap/issues/83)
* Terraform version: `terraform version`: Terraform v1.2.6
```hcl
data "ovh_cloud_project_capabilities_containerregistry_filter" "regcap_small" {
service_name = "xxxxxxxxxxx"
plan_name    = "SMALL"
region       = "GRA"
}
resource "ovh_cloud_project_containerregistry" "reg" {
service_name = data.ovh_cloud_project_capabilities_containerregistry_filter.regcap_small.service_name
plan_id      = …
```

feat: add OIDC configuration to containerRegistry

---

ovh/order.go
ovh/resource_cloud_project.go
ovh/types_me_order.go
website/docs/r/cloud_project.html.markdown

This PR fixes public cloud project creation for OVH US. It also improves cloud project documentation so that creation in the US is easier for end user.
Because of some differences in Agora, the result is different between OVH EU/CA on one side & OVH US on the other. There's been some internal discussions about changing that (I can provide more details in PM) and they haven't landed on a result and are not expected to in any near future.
This PR works around the issue by making extra call to find out serviceName if the initial serviceName determination attempt failed.
I manually tested it by successfully creating & importing a cloud project on OVH-US.
* Terraform version: `terraform version`: Terraform v1.4.2
``` bash
export …
```

fix(cloudProject): creation and import for cloudProject in the US

---

ovh/resource_cloud_project_test.go
website/docs/d/order_cart.html.markdown
website/docs/d/order_cart_product.html.markdown
website/docs/d/order_cart_product_options.html.markdown
website/docs/d/order_cart_product_options_plan.html.markdown
website/docs/d/order_cart_product_plan.html.markdown
website/docs/r/cloud_project.html.markdown
website/docs/r/hosting_privatedatabase.html.markdown
website/docs/r/ip_service.html.markdown
website/docs/r/iploadbalancing.html.markdown
website/docs/r/ovh_domain_zone.html.markdown
website/docs/r/vrack.html.markdown
website/docs/r/vrack_ip.html.markdown

Update the order documentation and sample to use [ovh_me](https://registry.terraform.io/providers/ovh/ovh/latest/docs/data-sources/me) datasource  and its subsidiary attribute instead of hardcoding the "fr"
Also remove the description attribute when it was used to be leaner ;-) 
- [X ] Documentation update

Improve the order documentation 

---

ovh/provider_test.go
ovh/resource_cloud_project_kube_test.go
website/docs/index.html.markdown

The `TestAccCloudProjectKubeUpdateVersion_basic` was using deprecated kubernetes version that was hardcoded. 
This PR adds a variable (`OVH_CLOUD_PROJECT_KUBE_PREV_VERSION_TEST`) to specify the previous version (compared to `OVH_CLOUD_PROJECT_KUBE_VERSION_TEST`)
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] `make testacc TESTARGS="-run TestAccCloudProjectKubeUpdateVersion_basic"`

Add a variable for the Managed Kubernetes Service upgrade test

---

.gitignore
examples/README.md
examples/kube-nodepool-deployment/README.md
examples/kube-nodepool-deployment/hello.yaml
examples/kube-nodepool-deployment/kube.tf
examples/kube-nodepool-deployment/provider.tf
examples/kube-nodepool-deployment/scripts/clean.sh
examples/kube-nodepool-deployment/scripts/create.sh
examples/kube-nodepool-deployment/variables.tf

Created a new section with coming examples in Terraform to deploy OVHcloud resources easily.
Added "Deploy an OVHcloud Manager Kubernetes cluster, a Node Pool and an application" example.

feat: add a full example with kube, node pool and an app

---

website/docs/r/me_ssh_key.html.markdown

Highlight the fact that the ovh ssh keys are currently not useable with Openstack resources
- [X ] Documentation update
N/A

Update in ssh key doc 

---

website/docs/d/dedicated_server_boots.html.markdown

Update the ovh_dedicated_server_boots documentation to add a missing parameter `kernel` which is defined but not exposed in the documentation.
Not tested this a documentation change

Update the ovh_dedicated_server_boots documentation

---

ovh/data_cloud_project_user_s3_credential.go
ovh/resource_cloud_project_user_s3_credential.go
ovh/resource_cloud_project_user_s3_credential_test.go
ovh/types_cloud.go

Fix the security update that removes S3 secret key from GET calls in OVH API.
Fixes #490
It has been tested to retrieve a user and check that the secret is properly returned.

fix(s3): fix s3 credentials secret retrieval

---

ovh/resource_domain_zone_record.go

When updating a resource of type `ovh_domain_zone_record`, an attribute `fieldtype` was set in the request body of the API call `PUT /domain/zone/{zoneName}/record/{id}`. This field is not declared in the API specifications so the updates end up in 400 HTTP error.

fix(ovh_domain_zone_record): attribute fieldtype doesn't exist in PUT request body

---

website/docs/r/ovh_domain_zone.html.markdown

Add documentation on how to import domain_zone resource
Fixes #481 
- [X ] Documentation update
* Terraform version: `terraform version`: Terraform v1.6.2
```hcl
data "ovh_me" "myaccount" {}
data "ovh_order_cart" "mycart" {
ovh_subsidiary = data.ovh_me.myaccount.ovh_subsidiary
}
data "ovh_order_cart_product_plan" "zone" {
cart_id        = data.ovh_order_cart.mycart.id
price_capacity = "renew"
product        = "dns"
plan_code      = "zone"
}
resource "ovh_domain_zone" "main" {
ovh_subsidiary = data.ovh_order_cart.mycart.ovh_subsidiary
plan {
duration     = data.ovh_order_cart_product_plan.zone.selected_price.0.duration
plan_code    = data.ovh_order_cart_product_plan.zone.plan_code
pricing_mode = …
```

add import documentation for zone

---

ovh/data_me_installation_template.go
ovh/data_me_installation_template_test.go

Fixes #497  : when a template was not found the data source launched a panic. 
- [X ] Test A: `make testacc TESTARGS="-run TestAccMeInstallationTemplateDataSource_basic"`

add acceptance test for a template name not found + fix the #497 issue

---

ovh/data_iam_policy.go
ovh/data_iam_policy_test.go
ovh/resource_iam_policy.go
ovh/resource_iam_policy_test.go
ovh/types_iam.go
website/docs/d/iam_policy.html.markdown
website/docs/r/iam_policy.html.markdown

This PR adds support for the "deny" permissions category in policies. This is the API endpoint to create policies : https://api.ovh.com/console-preview/?section=%2Fiam&branch=v2#post-/iam/policy
* Terraform version: `terraform version`: Terraform v1.6.2
```hcl
resource "ovh_iam_policy" "policy2" {
name        = "tf-test2"
description = "tf-test2"
identities  = ["urn:v1:eu:identity:user:<nic>/alice"]
resources   = ["urn:v1:eu:resource:publicCloudProject:<resourceID>"]
deny 	    = …
```

feat(iam): add support for deny in policies

---

ovh/data_iam_policy_test.go

Test `TestAccIamPolicyDataSource_basic` used an invalid IAM action `vrack:apiovh:dedicatedServer/remove` that caused the test to fail. Fixed it using IAM action `vrack:apiovh:dedicatedServer/detach`.

fix(TestAccIamPolicyDataSource_basic): Use an existing IAM action name

---

.cds/terraform-provider-ovh.yml
ovh/data_order_cart_product_options_plan_test.go

This PR fixes:
- Acceptance test `TestAccDataSourceOrderCartCloudOptionsPlan_basic` that used an invalid `optionCode` value
- The workflow that runs the acceptance tests. Until now, several tests using the same `vRack` service ran in parallel, which made the tests fail

fix failing acceptance tests

---

website/docs/r/cloud_project.html.markdown
website/docs/r/hosting_privatedatabase.html.markdown
website/docs/r/ip_service.html.markdown
website/docs/r/iploadbalancing.html.markdown
website/docs/r/ovh_domain_zone.html.markdown
website/docs/r/vrack.html.markdown

Fix documentation by stating that `BANK_ACCOUNT` payment method  is not supported anymore and shall be replaced by `SEPA_DIRECT_DEBIT`

fix #405 by stating that `BANK_ACCOUNT` is not anymore supported 

---

ovh/data_cloud_project_vrack.go
ovh/data_cloud_project_vrack_test.go
ovh/provider.go
ovh/types_cloud_project_vrack.go
website/docs/d/cloud_project_vrack.html.markdown

To prepare test for this issue https://github.com/ovh/terraform-provider-ovh/issues/402, i need data to get vrack for a public cloud project
```hcl
% make testacc TESTARGS="-run TestAccCloudProjectVrackDataSource_basic"                                                    
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccCloudProjectVrackDataSource_basic -timeout 600m -p 10
?       github.com/ovh/terraform-provider-ovh   [no test files]
?       github.com/ovh/terraform-provider-ovh/ovh/helpers       [no test files]
=== RUN   TestAccCloudProjectVrackDataSource_basic
--- PASS: TestAccCloudProjectVrackDataSource_basic (1.64s)
PASS
ok …
```

Datasource cloud public project vrack

---

ovh/resource_dbaas_logs_cluster_test.go

Fixes test `TestAccDbaasLogsCluster`: define the field `cluster_id` on the cluster resource

fix(TestAccDbaasLogsCluster): Set cluster_id property when creating a resource of type ovh_dbaas_logs_cluster

---

ovh/resource_dedicated_server_reboot_task_test.go
ovh/resource_dedicated_server_update_test.go

Use boot kernel `rescue-customer` in dedicated server tests as there are no results when using `rescue64-pro`.

fix: Use an existing boot kernel in dedicated server tests

---

go.mod
ovh/provider_new.go

While migrating to new terraform-sdk, regression has been introduced.
`terraform-plugin-sdk/v2` is changing value of Required/Optional schema variable when a DefaultFunc is provided, while the `terraform-plugin-framework` hasn't the same behavior, and crying about the schema difference.
Fixes #528.

fix: multi-provider doesn't allow Required/Optional to have different value

---

website/docs/index.html.markdown

Add in the documentation how a user can use an OVHcloud object storage to store its terraform state.
```
$ terraform version
Terraform v1.6.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/ovh/ovh v0.35.0
```
`backend.tf`:
```
terraform {
backend "s3" {
bucket = "terraform-state-hp"
key    = "terraform.tfstate"
region = "gra"
#or sbg or any activated high performance storage region
endpoints = {
s3 = "https://s3.gra.perf.cloud.ovh.net"
}
skip_credentials_validation = true
skip_region_validation = true
skip_requesting_account_id = true
}
}
```
```
$ terraform init
Initializing the backend...
Initializing provider plugins...
- Reusing previous version of ovh/ovh from the dependency lock …
```

[Doc] Add Terraform State storage in an OVHcloud Object Storage 

---

website/docs/index.html.markdown

Update the documentation  to explain to the user to use an OVHcloud object storage to store its terraform state.
```
$ terraform version
Terraform v1.6.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/ovh/ovh v0.35.0
```
`backend.tf`:
```
terraform {
backend "s3" {
bucket = "terraform-state-hp"
key    = "terraform.tfstate"
region = "gra"
#or sbg or any activated high performance storage region
endpoints = {
s3 = "https://s3.gra.perf.cloud.ovh.net"
}
skip_credentials_validation = true
skip_region_validation = true
skip_requesting_account_id = true
}
}
```
```
$ terraform init
Initializing the backend...
Initializing provider plugins...
- Reusing previous version of ovh/ovh from the …
```

[Doc] Update Terraform State storage doc to replace by a link to the official documentation

---

ovh/resource_dbaas_logs_cluster.go

This PR fixes an error when the state does not contain the `clusterId` and therefore avoid such error:
```
Error: Error calling GET /dbaas/logs/ldp-xxxx/cluster/: "json: cannot unmarshal array into Go value of type map[string]interface {}"
with ovh_dbaas_logs_cluster.foo
on main.tf line 110, in resource "ovh_dbaas_logs_cluster" "fooo": 
```

ovh_dbaas_logs_cluster: add lookup for default clusterId on Read resource

---

README.md

After analyzing, it appear that when we debug a provider, specifically an acceptance test, we can run several time our accaptance test but after the second run the acc test is cached.
So I added in the documentation a tips to skip/bypass go test caching.

[Docs] README: Info to run one acceptance test and bypass go test caching

---

ovh/data_dedicated_server.go
ovh/data_dedicated_server_test.go
ovh/resource_dedicated_server_update.go
ovh/resource_dedicated_server_update_test.go
ovh/types_dedicated_server.go
website/docs/d/dedicated_server.html.markdown
website/docs/r/dedicated_server_update.html.markdown

This PR adds for getting and setting the boot script
Fixes #546 (issue)
```hcl
data "ovh_dedicated_server_boots" "rescue" {
service_name = "nsxxxxxxx.ip-xx-xx-xx.eu"
boot_type    = "rescue"
kernel       = "rescue64-pro"
}
resource "ovh_dedicated_server_update" "server" {
service_name = "nsxxxxxxx.ip-xx-xx-xx.eu"
boot_script  = "TEST SCRIPT"
monitoring   = true
state        = "ok"
}
```

Add support for getting and updating boot script

---

ovh/resource_cloud_project.go

resource_cloud_project: factorize serviceName discovery and manage possible domain discrepancies
This PR aims at fixing possible race conditions on cloud project service name discovery.
In some cases, when project has been created through API (Terraform here), order gets messy and despite project being fully created, some order detail items have incorrect domain associated.
(I personally ended up with 5 order details item created, 3 of them having the correct projectId set as domain and 2 of them being set with domain "*001" (i.e. considered as US project).
The current code is naively considering only the first of the detail items as a reference for the project serviceName. Chances are that, based on how items are sorted, you either get a right or bad one (i.e. US one).
Note that even if …

resource_cloud_project: factorize serviceName discovery and manage possible domain discrepancies

---

ovh/data_cloud_project_vrack_test.go

Acceptance test `TestAccCloudProjectVrackDataSource_basic` was failing because it expects a vRack to be attached to the cloud project, which is not always the case.
This PR ensures that a vRack is attached before running, and detaches it afterwards.

fix: TestAccCloudProjectVrackDataSource_basic: Attach a vRack before test and detach it afterwards

---

.cds/terraform-provider-ovh.yml
README.md
ovh/helpers/helpers.go
ovh/provider.go
ovh/provider_test.go
ovh/resource_ip_move.go
ovh/resource_ip_move_test.go
ovh/types_ip.go
ovh/types_ip_service.go
website/docs/index.html.markdown
website/docs/r/ip_move.html.markdown

This adds a new add `ovh_ip_move` resource to move an IP to a provided service name or park it if empty service is given.
It relies on the following APIV6 routes:
- https://api.ovh.com/console/#/ip/service/%7BserviceName%7D~GET
- https://api.ovh.com/console/#/ip/%7Bip%7D/task/%7BtaskId%7D~GET
- https://api.ovh.com/console/#/ip/%7Bip%7D/move~POST
- https://api.ovh.com/console/#/ip/%7Bip%7D/park~POST
taken resource ID is the move task ID if available, or the IP itself otherwise
Moving/parking process:
- if there is an IpTask recorded in the resource state, we try to wait for it to be finished until it is considered expired
- after having waited until previous task expiration or completion, do the move only if the current service is different from the one given in the inputs
```shell
make …
```

feat(ip) - add ovh_ip_move resource to move an IP to a provided service name or park it if no service name given

---

ovh/data_dedicated_server.go
ovh/data_dedicated_server_test.go
website/docs/d/dedicated_server.html.markdown

Closes [#431](https://github.com/ovh/terraform-provider-ovh/issues/431)

feat: Add display_name to datasource ovh_dedicated_server

---

ovh/types_iploadbalancing.go

Fixes [#584](https://github.com/ovh/terraform-provider-ovh/issues/584)

fix: Allow update of field stickiness on resource ovh_iploadbalancing_tcp_farm

---

ovh/resource_iploadbalancing_http_frontend.go
ovh/resource_iploadbalancing_tcp_frontend.go

Fixes [#210](https://github.com/ovh/terraform-provider-ovh/issues/210)

fix: ipLoadbalancing use TypeSet for allowed_source and dedicated_ipfo

---

ovh/data_cloud_project_database.go
ovh/data_cloud_project_database_ip_restrictions.go
ovh/data_cloud_project_database_test.go
ovh/resource_cloud_project_database.go
ovh/resource_cloud_project_database_ip_restriction.go
ovh/resource_cloud_project_database_test.go
ovh/types_cloud_project_database.go
website/docs/d/cloud_project_database.html.markdown
website/docs/r/cloud_project_database.html.markdown

Following OVH API
- Add IP restriction in Database service resource and datasource
- Depracate ip_restriction resource and datasources

Ip restriction in database service + Deprecate old resource 

---

ovh/resource_cloud_project_failover_ip_attach.go

Fix issue with cloud_project_failover_ip_attach when updating `routed_to` on a resource

fix: cloud_project_failover_ip_attach: attaching to a new instance_id need to recreate the attach link

---

ovh/data_ip_firewall_rule.go
ovh/data_ip_firewall_rule_gen.go
ovh/data_ip_firewall_rule_test.go
ovh/resource_ip_firewall_rule.go
ovh/resource_ip_firewall_rule_gen.go
ovh/resource_ip_firewall_rule_test.go
website/docs/r/ip_firewall_rule.html.markdown

Fixes [#608](https://github.com/ovh/terraform-provider-ovh/issues/608) (issue)

fix: Use correct types for API response of resource/datasource ovh_ip_firewall_rule

---

ovh/resource_vrack_dedicated_server.go
website/docs/r/vrack_dedicated_server.html.markdown
website/docs/r/vrack_dedicated_server_interface.html.markdown

`ovh_vrack_dedicated_server` is not deprecated, still in use for legacy dedicated servers that do not have network interfaces.

fix: vrack: remove deprecation warning for non-deprecated resource

---

ovh/data_cloud_project_database.go
ovh/resource_cloud_project_database.go
ovh/types_cloud_project_database.go
website/docs/d/cloud_project_database.html.markdown
website/docs/r/cloud_project_database.html.markdown

- Fix an issue on Kafka update and/or create (when kafka_rest_api or advanced_configuration set).
- Kafka update API does not have `backups` field, this is a corner case of the resource `ovh_cloud_project_database`
- Add kafka_schema_registry attribute, following API
Fixe an issue reported directly to me.

fix kafka + add kafka_schema_registry attribute

---

ovh/resource_dedicated_server_install_task_test.go

Fix `TestAccDedicatedServerInstall` tests by using a real ssh key.

fix: Use a real ssh key for dedicated server tests + remove useless time_sleep resource

---

ovh/resource_cloud_project_user.go

`ovh_cloud_project_user`: field `role` is optional, so value should not be checked against the API if not defined.

fix: cloud_project_user: Don't check role is not given in config

---

ovh/resource_vrack_cloudproject_test.go

Test sweepers for resource `ovh_cloud_project_network_private` have been removed, so they must not be referenced as dependency in other resources tests.

fix: Remove sweepers dependency on ovh_vrack_cloudproject

---

ovh/order.go
ovh/resource_vrack.go
ovh/resource_vrack_test.go
ovh/types_service.go
website/docs/r/vrack.html.markdown

Change the way we import a vRack to use its `service_name` instead of its `order_id`.
Related to [#618](https://github.com/ovh/terraform-provider-ovh/issues/618)

feat: Update vRack to be imported by service_name instead of order_id

---

ovh/resource_cloud_project_gateway.go
ovh/resource_cloud_project_gateway_test.go
ovh/types_cloud.go
website/docs/r/cloud_project_gateway.html.markdown

* expose gateway's external information
* expose gateway's interfaces
* fix a mapping issue in the REST response of a gateway's external information
This is done to implement [this todo](https://github.com/ovh/terraform-provider-ovh/blob/f29ec136c6b9d2eeb2aa1fd492dc0b206923ce29/ovh/resource_cloud_project_gateway.go#L166).
Run locally using my own OVH public cloud account.
* Terraform version: `terraform version`: Terraform v1.8.2
```hcl
resource "ovh_cloud_project_network_private" "priv_net" {
service_name = var.ovh_project_number
name = "private_network" …
```

Expose gateway's external information and interfaces

---

website/docs/r/cloud_project_kube.html.markdown

Fixes some issues in the documentation for setting up managed Kubernetes with a private network (vRack).
I have a private project where I wanted to set up managed Kubernetes with vRack. It worked after these adjustments.

Fix documentation for kube with private network

---

ovh/data_me_identity_group.go
ovh/helpers/urn.go
ovh/resource_me_identity_group.go
ovh/types_me.go

- Add URN in datasource `ovh_me_identity_group`
- Use URN returned by the API in resource `ovh_me_identity_group`

fix: Use URN returned by the API for me_identity_group

---

website/docs/r/cloud_project.html.markdown

use correct datasource to order project with hds certification
Fixes #650 (issue)
```hcl
xx = "yy"
zz = "aa"
}
```

fix doc cloud hds #650

---

ovh/resource_iploadbalancing_tcp_frontend.go
ovh/resource_iploadbalancing_tcp_frontend_test.go
ovh/types_iploadbalancing.go
website/docs/r/iploadbalancing_tcp_frontend.html.markdown

Adds support for the [`deniedSource` parameter](https://eu.api.ovh.com/console-preview/?section=%2FipLoadbalancing&branch=v1#post-/ipLoadbalancing/-serviceName-/tcp/frontend) on the IPLB tcp frontends
Tested update/refresh on my IPLB LB2 with configuration :
* Terraform version: `terraform version`: Terraform v1.8.1
```hcl
resource "ovh_iploadbalancing_tcp_frontend" "frontend-rest-kmip" {
service_name    = data.ovh_iploadbalancing.iplb-a.service_name
display_name    = "${var.lbname}"
zone                  = var.region
port                   = "${var.rest_api_port}"
ssl                     = false
default_farm_id = ovh_iploadbalancing_tcp_farm.farm.id
allowed_source = var.allowed_sources …
```

feat(iplb): add support for deniedSource on tcp frontends

---

ovh/data_cloud_project_kube.go
website/docs/d/cloud_project_kube.html.markdown

Fixes an issue coming from https://github.com/ovh/terraform-provider-ovh/pull/661 : the added fields are missing in the related datasource.

fix: Add missing fields in ovh_cloud_project_kube datasource

---

go.mod
go.sum
ovh/config.go
ovh/provider.go
ovh/provider_new.go
vendor/github.com/ovh/go-ovh/ovh/configuration.go
vendor/github.com/ovh/go-ovh/ovh/ovh.go
vendor/modules.txt
website/docs/index.html.markdown

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #660
* Terraform version: `terraform version`: Terraform v1.8.5
```hcl
#
#
data "vault_generic_secret" "this" {
path = "secret/oauth2/self/ovh-eu"
}
provider "ovh" {
endpoint = var.ovh_endpoint
access_token = data.vault_generic_secret.this.data["access_token"]
}
data "ovh_me" "this" {}
output "ovh_me" {
value = data.ovh_me.this
}
```

feat: implement `access_token` auth method

---

ovh/resource_domain_zone_record.go
ovh/resource_domain_zone_record_test.go

fix: ovh_domain_zone_record: use correct default value for ttl

---

ovh/resource_dedicated_server_install_task.go

When creating an install task, the returned error is ignored. We then try to fetch the task many times, even if the task was not created.
Fixes #671

fix: resource DedicatedServerInstallTask: don't retry task if creation failed

---

ovh/resource_domain_zone_record.go
ovh/resource_domain_zone_record_test.go

Fixes two issues on resource `ovh_domain_zone_record`:
- When `ttl` is set to `0`, it is not sent at record creation
- Wrong error assertion in acceptance test

fix: ovh_domain_zone_record: wrong assertion in test + 0 ttl not sent

---

ovh/data_dbaas_logs_output_graylog_stream.go
ovh/data_dbaas_logs_output_graylog_stream_test.go
ovh/resource_dbaas_logs_output_graylog_stream.go
ovh/resource_dbaas_logs_output_graylog_stream_test.go
ovh/types_dbaas_logs_output_graylog_stream.go
website/docs/d/dbaas_logs_output_graylog_stream.html.markdown
website/docs/r/dbaas_logs_graylog_output_stream.html.markdown

Added field `write_token` in resource and datasource `ovh_dbaas_logs_output_graylog_stream`.
Fixes #686

feat: add write_token field in resource/datasource ovh_dbaas_logs_output_graylog_stream

---

ovh/data_dbaas_logs_cluster.go
ovh/data_dbaas_logs_cluster_test.go

When not defined in the configuration, the field `cluster_id` of datasource `ovh_dbaas_logs_cluster` was not set.

fix: correctly set cluster_id field in datasource ovh_dbaas_logs_cluster

---

.cds/terraform-provider-ovh.yml
ovh/data_cloud_project_region_loadbalancer_log_subscription_test.go
ovh/data_cloud_project_region_loadbalancer_log_subscriptions_test.go
ovh/resource_cloud_project_region_loadbalancer_log_subscription.go
ovh/resource_cloud_project_region_loadbalancer_log_subscription_test.go
ovh/types_cloud_project_region_loadbalancer.go
website/docs/index.html.markdown

Fix tests of resource/datasources `ovh_cloud_project_region_loadbalancer_log_subscription`.

fix: CloudProjectLoadbalancerLogSubscription tests were failing

---

ovh/data_hosting_privatedatabase_whitelist.go
ovh/resource_hosting_privatedatabase_whitelist.go
ovh/types_hostingPrivatedatabase.go

OVH API v6 authorize to create a whitelist without a nemask but will add it if it's undefined.
Then, when you execute a plan/apply it throws an error
```sh
module.whitelist[0].ovh_hosting_privatedatabase_whitelist.whitelist: Creating...
╷
│ Error: calling /hosting/privateDatabase/om55704-038/whitelist/5.196.197.1:
│        OVHcloud API error (status code 400): Client::BadRequest: "[ip] Given data (w.x.y.z) is not valid for type ipv4Block" (X-OVH-Query-Id: EU.ext-xxxx)
│ 
│   with module.whitelist[0].ovh_hosting_privatedatabase_whitelist.whitelist,
│   on ../../modules/whitelist/main.tf line 1, in resource "ovh_hosting_privatedatabase_whitelist" "whitelist":
│    1: resource "ovh_hosting_privatedatabase_whitelist" "whitelist" {
│ 
```
Please …

fix(hosting_privatedatabase_whitelist): Add default netmask when user do not define it

---

ovh/helpers/json.go
ovh/resource_cloud_project_user_s3_policy.go
ovh/resource_cloud_project_user_s3_policy_test.go
ovh/testing.go

fix: ovh_cloud_project_user_s3_policy: Read policy field from API

---

ovh/order.go
ovh/provider_test.go
ovh/resource_cloud_project.go
ovh/resource_cloud_project_test.go
ovh/types_me_order.go
ovh/types_service.go

Retrieve the `configurations` given at order time in resource `ovh_cloud_project`.
Fixes #704

fix: Fetch plan configurations when reading orders

---

ovh/data_me_installation_template.go
ovh/resource_dedicated_server_install_task.go
ovh/resource_me_installation_template.go
ovh/resource_me_installation_template_test.go
ovh/types_dedicated_server.go
ovh/types_installation_template.go
website/docs/d/dedicated_server_boots.html.markdown
website/docs/d/me_installation_template.html.markdown
website/docs/r/dedicated_server_install_task.html.markdown
website/docs/r/me_installation_template.html.markdown

Update dedicated server install task in order to remove deprecated stuff (post installation script, HardRaidConfiguration boolean and IpxeCustomerScript from boot_type)  
* Terraform version: `terraform version`: Terraform 1.6.6
a dedicated server

Update dedicated post install script

---

ovh/resource_vrack.go
ovh/resource_vrack_test.go
website/docs/r/vrack.html.markdown

vRacks can now be terminated, so this PR adds removal capability on `ovh_vrack` resource.

feat: Allow vrack resource removal since termination is now available on the API

---

ovh/resource_iploadbalancing_http_farm.go
website/docs/r/iploadbalancing_http_farm.html.markdown

The IPLB HTTP farm resource should be able to use "uri" as a possible balance value.
- [*] Bug fix (non-breaking change which fixes an issue)
reference: https://eu.api.ovh.com/console/?section=%2FipLoadbalancing&branch=v1#post-/ipLoadbalancing/-serviceName-/http/farm

IPLB HTTP farm resource: added uri as a possible balance value

---

ovh/resource_dbaas_logs_input.go
ovh/resource_dbaas_logs_input_test.go
ovh/types_dbaas_logs_input.go
website/docs/r/dbaas_logs_input.html.markdown

fix: Add missing autoscaling params to resource ovh_dbaas_logs_input

---

website/docs/r/vrack.html.markdown

It appears that we can't name a vrack "my name".
```
$ terraform apply
data.ovh_me.myaccount: Reading...
data.ovh_me.myaccount: Read complete after 0s [id=xxxxxxx-ovh]
data.ovh_order_cart.mycart: Reading...
data.ovh_order_cart.mycart: Read complete after 0s [id=xxxxx-xxxx-xxxx-xxxx-xxxxxxxx]
data.ovh_order_cart_product_plan.vrack: Reading...
data.ovh_order_cart_product_plan.vrack: Read complete after 0s [id=vrack]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "ovh_vrack" "vrack" {
+ description    = "my vrack"
+ id             = (known after apply)
+ name           = "my vrack"
+ ovh_subsidiary = "FR"
+ service_name   = (known after …
```

[DOC] Fix vrack name allowed

---

ovh/resource_iploadbalancing_ssl_gen.go
ovh/resource_iploadbalancing_ssl_test.go
website/docs/r/iploadbalancing_ssl.html.markdown

ovh_iploadbalancing_ssl: Changing service_name, certificate, key or chain must trigger a full replace

fix definition of ovh_iploadbalancing_ssl

---

ovh/helpers/helpers.go
ovh/provider.go
ovh/resource_cloud_project_network_private_subnet_v2.go
ovh/resource_cloud_project_network_private_subnet_v2_test.go
ovh/resource_cloud_project_workflow_backup_test.go
ovh/resource_dedicated_server_install_task.go
ovh/resource_hosting_privatedatabase.go
ovh/types_cloud.go
website/docs/r/cloud_project_network_private_subnet_v2.html.markdown

Add a new regionalized resource ovh_cloud_project_network_private_subnet_v2, it is not really a v2, but a regionalized subnet, so it may be preferable to call it ovh_cloud_project_network_private_subnet_on_region or something like this...
Related to https://github.com/ovh/public-cloud-roadmap/issues/582
```hcl
resource "ovh_cloud_project_network_private_subnet_v2" "subnet" {
service_name      = ovh_cloud_project_network_private.network.service_name
name …
```

subnet v2 resource (regionalized API)

---

ovh/helpers/helpers.go

Add request ID in error message when CheckDeleted function is used. This information is systematically asked by the support but isn't available anywhere in a normal run
-  Improvement (improve existing resource(s) or datasource(s))
Just waited for one of the occasionnal API fail

Improve error message : add request ID

---

ovh/resource_cloud_project_database_test.go
ovh/types_cloud_project_database.go
website/docs/r/cloud_project_database.html.markdown

fix: ovh_cloud_project_database: prevent setting backup_time on some engines

---

ovh/resource_cloud_project.go
ovh/resource_cloud_project_test.go
ovh/resource_domain_zone.go
ovh/resource_domain_zone_test.go
ovh/resource_hosting_privatedatabase.go
ovh/resource_hosting_privatedatabase_test.go
ovh/resource_iploadbalancing.go
ovh/resource_iploadbalancing_test.go
ovh/resource_vrack.go
ovh/resource_vrack_test.go
website/docs/r/cloud_project.html.markdown
website/docs/r/domain_zone.html.markdown
website/docs/r/iploadbalancing.html.markdown

Resources that are created using an order used the `orderId` as ID. This is impractical and forces the users to retrieve the order ID to import the resources. This PR changes this to use the `service_name` as ID of these resources.
It also avoids making many calls in Read/Update/Delete functions to retrieve the service name each time.
Ran tests related to these resources.

fix: Stop using orderId as ID of resources created via an order, use serviceName instead

---

website/docs/r/cloud_project_region_storage_presign.html.markdown

- Remove the note on cloud_project_region_storage_presign resource telling it's compatible only with the High Performance storage class. Pre-signed URLs are compatible with any class.
- Region name must be in uppercase
- Documentation update

docs: Presign URLs are compatible with any storage class

---

website/docs/r/cloud_project.html.markdown

doc: Add an example of cloud project creation with a pre-existing vrack

---

ovh/resource_okms.go
ovh/resource_okms_credential_test.go
ovh/resource_okms_gen.go
ovh/resource_okms_service_key_test.go
ovh/resource_okms_test.go
website/docs/r/okms.html.markdown

In order to support the change in the region format from PLATE_LOCATION_DC to plate-location-dc we need to add some custom handling for the KMS region parameter :
- Never recreate the kms when we only have a region format mismatch, update it instead.
- On update, use the value from the plan for the region. (which can only happen in case of a format mismatch)
- Warn when the old format is used

feat(okms): support the new region name format

---

ovh/resource_cloud_project_kube_test.go
website/docs/r/cloud_project_kube.html.markdown

* remove `ovh_vrack_cloudproject` resource  since from Q2 2024 all public cloud projects (existing or new) have a vrach attached to them.
* remove unnecessary `depends_on` that terraform / opentofu engine can manage.
* add `node_subnet_id` to avoid race condition in terraform execution plan if the subnet & the kube cluster are created in // resulting in error like `Private network xxx does not have any subnet`
* add a managed gateway
* in the test, add a random vlanId for a smoother run.
- [ X] Documentation update
- [ X] Test A: `make testacc TESTARGS="-run …

Clean test and example on cloud_project_kube resource with private network

---

ovh/resource_dbaas_logs_input.go
ovh/resource_dbaas_logs_input_test.go
ovh/types_dbaas_logs_input.go

fix: Use Set instead of List in ovh_dbaas_logs_input.allowed_networks

---

ovh/resource_cloud_project_failover_ip_attach.go

fix: Retry failover IP attach to cloud project

---

ovh/resource_cloud_project_network_private_subnet_v2.go
ovh/resource_cloud_project_network_private_subnet_v2_test.go
ovh/types_cloud.go
website/docs/r/cloud_project_network_private_subnet_v2.html.markdown

Add use_default_public_dns_resolver in subnetv2
```hcl
resource "ovh_cloud_project_network_private_subnet_v2" "subnet" {
network_id        = "aaa-vvv-bbb-ccc"
name              = "my_private_subnet"
region            = "BHS5"
dns_nameservers   = ["1.1.1.1"]
cidr              = "192.168.168.0/24"
dhcp              = true
enable_gateway_ip = true
use_default_public_dns_resolver = false
}
```
```
+ resource "ovh_cloud_project_network_private_subnet_v2" …
```

add subnet usedefault public dns

---

ovh/resource_ip_firewall_rule.go
ovh/resource_ip_firewall_rule_test.go
website/docs/r/ip_firewall_rule.html.markdown

feat: Add import capability to resource ovh_ip_firewall_rule

---

ovh/resource_savings_plan.go
ovh/resource_savings_plan_test.go
website/docs/r/savings_plan.html.markdown

chore: Uppercase flavors when searching for savings plans in resource ovh_savings_plan

---

ovh/resource_cloud_project_volume.go
ovh/resource_cloud_project_volume_gen.go
ovh/resource_cloud_project_volume_test.go
website/docs/r/cloud_project_region_volume.markdown

fix: Allow size edition in resource ovh_cloud_project_volume

---

go.mod
go.sum
ovh/data_dbaas_logs_cluster_retention.go
ovh/data_dbaas_logs_cluster_retention_gen.go
ovh/data_dbaas_logs_cluster_retention_test.go
vendor/github.com/hashicorp/terraform-plugin-framework-validators/internal/schemavalidator/also_requires.go
vendor/github.com/hashicorp/terraform-plugin-framework-validators/internal/schemavalidator/at_least_one_of.go
vendor/github.com/hashicorp/terraform-plugin-framework-validators/internal/schemavalidator/conflicts_with.go
vendor/github.com/hashicorp/terraform-plugin-framework-validators/internal/schemavalidator/exactly_one_of.go
vendor/github.com/hashicorp/terraform-plugin-framework-validators/listvalidator/no_null_values.go
vendor/modules.txt
website/docs/d/dbaas_logs_cluster_retention.html.markdown

A new field has been added on API side: `retentionType`. This PR adds it in datasource `ovh_dbaas_logs_cluster_retention` to be able to filter retentions on the right type.

feat: Add retention_type to datasource ovh_dbaas_logs_cluster_retention

---

ovh/resource_cloud_project_network_private_subnet_v2.go
ovh/resource_cloud_project_network_private_subnet_v2_test.go

fix: Set the right property name for allocation pools in ovh_cloud_project_network_private_subnet_v2

---

ovh/data_dedicated_nasha.go
ovh/data_dedicated_nasha_partition.go
ovh/provider.go
ovh/types_dedicated_nasha.go
website/docs/d/dedicated_nasha.html.markdown
website/docs/d/dedicated_nasha_partition.html.markdown

This pull request adds a new computed field partitions_list to the ovh_dedicated_nasha data source. The field is populated by calling the GET /dedicated/nasha/{serviceName}/partition endpoint, which returns an array of partition names ([]string). This change allows users to retrieve all partition names for a given NAS-HA service in their Terraform configurations.
Allows Terraform users to dynamically fetch and manage partitions for a specific NAS-HA service.
Enhances the data source by providing more detailed information about the partitions available.
No additional dependencies are required beyond the existing OVH client library.

With new datasource : ovh_dedicated_nasha_partition

---

ovh/data_dedicated_server.go
ovh/data_dedicated_server_test.go
ovh/resource_dedicated_server_gen.go
ovh/resource_dedicated_server_install_task_test.go
ovh/resource_dedicated_server_test.go
ovh/resource_dedicated_server_update.go
ovh/resource_dedicated_server_update_test.go
ovh/types_dedicated_server.go
website/docs/d/dedicated_server.html.markdown
website/docs/r/dedicated_server.html.markdown
website/docs/r/dedicated_server_update.html.markdown

Add efiBootloaderPath for dedicated server resource & dedicated server update
Possibility to GET and PUT the efi_bootloader_path on a dedicated server
* Terraform version: `terraform version`: Terraform 1.6.6
```hcl
a dedicated serer
}
```

Add efiBootloaderPath for dedicated server resource & update

---

website/docs/r/ip_service.html.markdown

fix: Add missing configurations in ovh_ip_service doc

---

ovh/provider.go
ovh/resource_vrack_ipv6.go
ovh/resource_vrack_ipv6_test.go
website/docs/r/vrack_ipv6.html.markdown

Add resource `ovh_vrack_ipv6`.

feat: Add resource ovh_vrack_ipv6

---

ovh/provider.go
ovh/resource_vrack_vrackservices.go
ovh/resource_vrack_vrackservices_test.go
ovh/types_vrack.go
website/docs/r/vrack_vrackservices.html.markdown

Add resource `ovh_vrack_vrackservices`.

feat: Add resource ovh_vrack_vrackservices

---

ovh/resource_cloud_project_instance_test.go

Test was using a bad set of input variables.

fix ovh_cloud_project_instance 3AZ test

---

ovh/resource_dedicated_server_reinstall_task.go
ovh/types_dedicated_server.go

Fixes software raid type that was not sent to the API calls when the value is `0`.
Fixes #906 (issue)

fix: Send the right raid_level in dedicated reinstall task

---

ovh/resource_cloud_project_loadbalancer_gen.go
ovh/resource_cloud_project_loadbalancer_test.go

Fixes resource `ovh_cloud_project_loadbalancer`: the wrong values were sent to the API call to create a loadbalancer (null values were sent), and there were incorrect `computed: true` in the schema.
Fixes #905 (issue)

fix: Right API calls and schema for cloud_project_loadbalancer

---

docs/data-sources/cloud_project_instance.md
docs/data-sources/cloud_project_instances.md
docs/resources/cloud_project_instance.md
ovh/data_cloud_project_instance.go
ovh/data_cloud_project_instances.go
ovh/resource_cloud_project_instance.go
ovh/resource_cloud_project_instance_test.go
ovh/types_cloud.go
ovh/types_cloud_project_instance.go
templates/data-sources/cloud_project_instance.md.tmpl
templates/data-sources/cloud_project_instances.md.tmpl
templates/resources/cloud_project_instance.md.tmpl

Allow creating a `ovh_cloud_project_instance` on a private network, and wait for it to be ready after creation.
Fixes #915 (issue)

feat: Allow creating an instance on a private network

---

docs/guides/dedicated_server_migration.md
go.sum
ovh/order_resource_gen.go
ovh/resource_dedicated_server.go
ovh/resource_dedicated_server_gen.go
website/docs/r/dedicated_server.html.markdown

Add the new installation parameters (first introduced in v2.0.0) in resource `ovh_dedicated_server` to allow a smooth migration from v1.6.0 to v2.0.0.
This PR also adds a migration guide.

feat: Allow smooth migration for ovh_dedicated_server resource

---

ovh/resource_cloud_project_database_test.go
ovh/types_cloud_project_database.go

When updating a cloud database, an error is returned if `backup_time` is set for an engine for which this parameter cannot be configured. This error is returned even when the field is only set in the state but not configured by the user.
This PR modifies this behavior to error only when the user has manually updated the value.
Fixes #935 (issue)

fix(ovh_cloud_project_database): Don't error when backup_time is only set in state for an engine that doesn't handle the parameter

---

ovh/types_iploadbalancing.go

Allow to reset iploadbalancing farm and farm server port property to null
Tested by creating and updating farm and farm server with port and updating it with null port

fix: allow reset iploadbalancing farm and farm server port to null

---

docs/resources/dbaas_logs_input.md
examples/resources/dbaas_logs_input/example_1.tf
ovh/data_dbaas_logs_input_engine_test.go

For `dbaas_logs_input_engine`, the default & documented values (`7.x`) is a bit old and deprecated. Lets move it to `9.x`.
Nop

fix: dbaas_logs_input_engine default & documented version

---

docs/resources/cloud_project_instance.md
examples/resources/cloud_project_instance/timeout.tf
ovh/resource_cloud_project_instance.go
ovh/resource_cloud_project_loadbalancer.go
ovh/resource_cloud_project_region_network.go
ovh/types_cloud.go
ovh/types_cloud_project_instance.go
templates/resources/cloud_project_instance.md.tmpl

This PR adds the ability to customize the timeout for `ovh_cloud_project_instance` resource creation.
Fixes #956 (issue)

feat: Add customizable creation timeout for ovh_cloud_project_instance

---

docs/resources/cloud_project_user.md
templates/resources/cloud_project_user.md.tmpl

This PR adds missing roles in the doc of resource `ovh_cloud_project_user`.
Fixes #901 (issue)

fix: Add missing roles to ovh_cloud_project_user

---

.cds/terraform-provider-ovh-check.pip.yml
.cds/terraform-provider-ovh-run-sweepers.pip.yml
.cds/terraform-provider-ovh-testacc.pip.yml

Use Go 1.23 in worker models to run tests in CI.

fix: Use go-1.23 worker model in CI

---

docs/index.md
ovh/config.go
ovh/provider.go
ovh/provider_new.go
templates/index.md.tmpl

Allow defining a `user_agent_extra` field in provider configuration to append extra information in the `user-agent` header in API calls.
Fixes #916 (issue)

feat: Allow adding custom info to user-agent

---

docs/resources/cloud_project_user.md
examples/resources/cloud_project_user/example_2.tf
ovh/resource_cloud_project_user.go
ovh/resource_cloud_project_user_test.go
ovh/types_cloud.go
templates/resources/cloud_project_user.md.tmpl

This PR introduces a password rotation mechanism for the ovh_cloud_project_user resource. A new optional attribute rotate_when_changed has been added. When any key/value pair within this map changes, the provider will trigger the OVHcloud API to regenerate the user's password without recreating the user resource itself.
This allows for scheduled or event-driven password rotation. The new password is stored in the Terraform state, making it available for use by other resources (e.g., storing it securely).
Fixes #962 
go test -v ./ovh -run '^TestAccCloudProjectUser_.*$' -timeout 30m
```
=== RUN   TestAccCloudProjectUser_basic
provider_test.go:506: Read Cloud Project /cloud/project/aa2425907763475a89a4bf4e9f9e22fb -> status: 'ok', desc: 'itsc-test-rollout'
--- PASS: …
```

feat: Add support for password rotation in cloud project user resource

---

ovh/types/int64.go
ovh/types/number.go

Function `Equal` was missing on custom types `TfInt64Value` and `TfNumberValue`, which caused invalid diff between state and plan when used.

fix: Add missing Equal methods on types TfInt64Value and TfNumberValue

---

docs/resources/vrack_ip.md
docs/resources/vrack_ipv6.md
ovh/provider_test.go
ovh/resource_vrack_ip.go
ovh/resource_vrack_ip_test.go
ovh/resource_vrack_ipv6.go
ovh/resource_vrack_ipv6_test.go
ovh/types_vrack.go
templates/resources/vrack_ip.md.tmpl
templates/resources/vrack_ipv6.md.tmpl

Add region argument for POST /vrack/{serviceName}/ip
Region will also be added in IPv6 as a returned value for  GET /vrack/{serviceName}/ipv6/{ipv6}
* Terraform version: `terraform version`: Terraform v1.11.1
```hcl
resource "ovh_vrack_ip" "vrack_block" {
service_name = {vRack}
block        =  {Blockv4}
region       = {region}
}
```

feat(vrack): add region argument to post block

---

docs/resources/savings_plan.md
ovh/resource_savings_plan.go
templates/resources/savings_plan.md.tmpl

This PR add a default to the `service_name` argument for the savings_plan resource.
It's using the `OVH_CLOUD_PROJECT_SERVICE`, similar to what other resources do (see [data_cloud_project_vrack.go](https://github.com/ovh/terraform-provider-ovh/blob/master/ovh/data_cloud_project_vrack.go#L21C5-L21C74))

feat(saving-plans): add default service_name using OVH_CLOUD_PROJECT_SERVICE

---

docs/resources/cloud_project_database_log_subscription.md
docs/resources/dedicated_server.md
ovh/resource_dedicated_server.go
ovh/resource_dedicated_server_gen.go
templates/resources/dedicated_server.md.tmpl

Add `reboot_rescue` option in `ovh_dedicated_server` pre-destroy available actions.

feat: Add reboot_rescue option in ovh_dedicated_server pre-destroy available actions

---

ovh/provider_test.go
ovh/resource_cloud_project_instance_test.go
ovh/types_cloud_project_instance.go

fix: Send the correct floatingIp information when creating an instance

---

ovh/resource_ip_firewall_gen.go

Using the following resource:
```hcl
resource "ovh_ip_firewall" "iplb_firewall" {
ip             = "x.x.x.x/32"
ip_on_firewall = "x.x.x.x"
enabled        = true
} 
```
Leads to the following error: `Received not described parameters:│ (enabled) while calling creation handler`
The `enabled` field is sent in the `Create` request, which is not allowed in the API: [POST /ip/{ip}/firewall](https://eu.api.ovh.com/console/?section=%2Fip&branch=v1#post-/ip/-ip-/firewall)
* Existing HCL configuration you …

fix(resource_ip_firewall): "enabled" field should only be sent when updating firewall

---

CONTRIBUTING.md

I noticed the links didn't match the templates anymore and also added links to all templates

Fix links to open issues to include correct template parameter

---

ovh/data_cloud_project_instance_test.go

fix: Use the right env var for instance ID in TestAccDataSourceCloudProjectInstance_basic

---

ovh/resource_dedicated_server.go
ovh/resource_dedicated_server_gen.go

When updating string parameters of a dedicated server, only send an empty string when the parameter had a previous value and was removed.

fix(ovh_dedicated_server): Don't always send empty strings when updating parameters

---

docs/resources/vps.md
examples/resources/vps/example_1.tf
ovh/provider_test.go
ovh/resource_vps.go
ovh/resource_vps_gen.go
ovh/resource_vps_test.go
templates/resources/vps.md.tmpl

Introducing new attributes `public_ssh_key` and `image_id` on `vps` resource allowing to call the `/rebuild` API endpoint on an existing VPS server, especially useful to update the default SSH key configured on that server.
Fixes #943 (issue)

feat(vps-reinstall): new resource to be able to reinstall VPS server

---

docs/data-sources/cloud_project_user_s3_credential.md
docs/data-sources/cloud_project_user_s3_credentials.md
docs/data-sources/cloud_project_user_s3_policy.md
docs/resources/cloud_project_user_s3_credential.md
docs/resources/cloud_project_user_s3_policy.md
templates/data-sources/cloud_project_user_s3_credential.md.tmpl
templates/data-sources/cloud_project_user_s3_credentials.md.tmpl
templates/data-sources/cloud_project_user_s3_policy.md.tmpl
templates/resources/cloud_project_user_s3_credential.md.tmpl
templates/resources/cloud_project_user_s3_policy.md.tmpl

Move guides about S3 to Object Storage subcategory (it's not easy to find them now).

[Docs] Move s3 docs to object storage category

---

docs/resources/dedicated_server.md
docs/resources/dedicated_server_update.md
ovh/resource_dedicated_server_gen.go
ovh/resource_dedicated_server_update.go
templates/resources/dedicated_server.md.tmpl
templates/resources/dedicated_server_update.md.tmpl

When updating `serviceName` field on resources `ovh_dedicated_server` and `ovh_dedicated_server_update`, they should be recreated.
Fixes #1030 (issue)

fix: Add missing ForceNew on serviceName on resources ovh_dedicated_server and ovh_dedicated_server_update

---

ovh/resource_savings_plan.go

Currently API route will return any match, for instance B3-64 search will match B3-64 and B3-640
```hcl
resource "ovh_savings_plan" "plan" {
service_name = "xxx"
flavor = "B3-64"
period = "P1M"
size = 1
display_name = "xxx"
auto_renewal = false
}
```

fix: match exact product code

---

docs/resources/dbaas_logs_token.md
examples/resources/dbaas_logs_token/example_2.tf
ovh/resource_dbaas_logs_token.go
templates/resources/dbaas_logs_token.md.tmpl

Add ability to import resource `ovh_dbaas_logs_token`.
Fixes #1025 (issue)

feat: Add import capability to ovh_dbaas_logs_token

---

docs/resources/dbaas_logs_input.md
examples/resources/dbaas_logs_input/example_1.tf

The example configuration (`ssl` vs `ssl_enabled`) is misaligned with the example's logstash version (`9.x`)
Nope

doc: fix dbaas_logs input example

---

ovh/resource_cloud_project_failover_ip_attach.go

- Explicit message when trying to attach failover IP outside of the current cloud project
- apply now fails when the attach is not successful
Fixes #1050 (issue)

fix: error management on cloud_project_failover_ip_attach

---

docs/resources/vps.md
templates/resources/vps.md.tmpl

Add documentation on `vps`resource OS setup, with emphasis on the distinctive usage of `image_id` attribute for reinstallation versus `plan.configuration` at creation.
Fixes #1049 (issue)
Not relevant

chore(docs): clarifications in vps image selection

---

docs/resources/cloud_project_storage.md
docs/resources/vps.md
ovh/resource_cloud_project_region_storage_gen.go
ovh/resource_cloud_project_storage_test.go
templates/resources/cloud_project_region.md.tmpl
templates/resources/cloud_project_storage.md.tmpl

`ovh_cloud_project_storage`: Field `tags` in the replication filters is a map.
Fixes #1023 (issue)

fix(ovh_cloud_project_storage): Set the right type for replication tags

---

ovh/resource_domain_zone_record.go

fix: Correctly recreate resource ovh_domain_zone_record when deleted outside Terraform

---

ovh/resource_cloud_project_instance_test.go

Fix test `TestAccCloudProjectInstance_privateNetworkCreate` to make it use a random vlan ID.

fix: Use a random vlan ID in TestAccCloudProjectInstance_privateNetworkCreate

---

docs/data-sources/cloud_project_kube.md
examples/data-sources/cloud_project_kube/example_1.tf
ovh/data_cloud_project_kube.go
ovh/data_cloud_project_kube_test.go
templates/data-sources/cloud_project_kube.md.tmpl

The cloud-project-kube data source can now return kubeconfig and kubeconfig_attributes as sensitive data (which are already returned by the resource during the creation).
This can be useful when you want to reuse an existing kube cluster in another project.
I've followed the `Readme` -> `Using the locally built provider` part, and test it with a project that need to get an existing kube project + update the existing unit tests.

feat: cloud-project-kube data source now expose kubeconfig and kubeconfig_attributes as sensitive data

---

docs/resources/cloud_project_user.md
docs/resources/cloud_project_volume.md
examples/resources/cloud_project_user/example_3.tf
examples/resources/cloud_project_volume/example_1.tf
examples/resources/cloud_project_volume/example_2.tf
ovh/resource_cloud_project_user_test.go
ovh/resource_cloud_project_volume.go
ovh/resource_cloud_project_volume_test.go
templates/resources/cloud_project_user.md.tmpl
templates/resources/cloud_project_volume.md.tmpl

- Add import capability to resource `ovh_cloud_project_volume`
- Add import documentation for resource `ovh_cloud_project_user`
Fixes #1093 (issue)

feat: Add import to ovh_cloud_project_volume and ovh_cloud_project_user

---

docs/data-sources/cloud_project_database.md
docs/resources/cloud_project_database.md
ovh/data_cloud_project_database.go
ovh/resource_cloud_project_database.go
ovh/types_cloud_project_database.go
templates/data-sources/cloud_project_database.md.tmpl
templates/resources/cloud_project_database.md.tmpl

Deletion Protection option for cloud Database service
Tested with this code then try to delete it manualy and by remove the resource to my Terraform code to check that an error is returned and block the deletion.
```hcl
resource "ovh_cloud_project_database" "database" {
service_name        = "xxxxxxx
engine              = "postgresql"
description         = "lucky-yang"
flavor              = "db1-7"
nodes {
region     = "GRA"
}
deletion_protection = true
plan                = "essential"
version             = "17"
}
```

add deletion protection field for database service
